### PR TITLE
WIP: Preliminary investigation: updating to python 3

### PR DESCRIPTION
**Pull request by drewsilcock**
So far:

- Moved dependencies over to Poetry (just made the process much easier with proper dependency resolution, doesn't need to be permanent change).
- Run 2to3 and hand-pick output to check for false positives. (Haven't run through every line of code to check for false negatives).
- Initial changes to fix immediate issues (blocked by not being able to import `reporters_db` currently, there's bound to be more issues after that though).
- Upgrade dependencies as required to get them installed on py3.8.

When porting code I tend to take this approach:

1. Upgrade dependencies until they install
2. Try to run code
3. It breaks
4. Fix where it breaks
5. Try to run code again
6. It breaks in a different place
7. Fix where it breaks again
8. Run it again: it breaks => goto 6. else continue
9. It works
10. Celebrate
11. Ah but this bit doesn't work... => goto 6
12. You get the idea

Next steps:

- Use `mypy` for an additional level of checking to find more issues without needing to run every line of code.
- Getting `reporters_db` installed and working on py3 so that we can continue with the porting cycle.

If you want to discuss any of these changes and potential problems, here's a good place to do it! 🙂

### CODE REVIEW

**Comment by flooie** [comment]
Hi @drewsilcock great work.  I took a quick look and I don't see why reporters-db would be a blocker.  It does not have python-dateutil as a dependency.  Could it be something else blocking?

**Comment by drewsilcock** [comment]
Yes you're right it's juriscraper that depends on `python-dateutil==2.5.0` not reporters-db.

**Comment by mlissner** [comment]
I'm giving this a big look. So far, frankly, it's incredible to see. This is just thrilling stuff. A couple notes, of course, though:

1. Anything in scripts_archive should just be deleted. I don't know why those exist. If you don't mind nuking those, that'd be great. One less thing to review.

2. You mention `mypy`. I thought Python 3 had static typing built in?

3. More cleanup is needed for the old requirements file (and the docker images and ansible scripts that need them, I think).

I think that's kind of it. Can we trust that with the switch to poetry we will successfully avoid any dependency pain? I'm kind of amazed you cranked out a list of the dozen or so req's with issues.

Are you using some kind of checklist for this?

**Comment by mlissner** [comment]
@flooie is offline for a bit and I have to change gears, but he tells me that he got Juriscraper installed by tweaking urllib slightly:

```
# from urlparse import urlparse
import urllib.parse
```

I read through dateutil's changelog and I don't see any issues with upgrading all the way to the highest 2.x.x. I haven't read their changelog before, it's ride. Incredible how hard it is to do stuff with dates.

**Comment by flooie** [comment]
@drewsilcock I branched a quick and dirty version of juriscraper branch py38 that installed and functions fine. 

Also I merged your code and was able to get the 60% or so of our tests to pass.  Im not sure if its helpful or not but check out branch python38-merger if you are interested.

**Comment by drewsilcock** [comment]
Thanks for taking a look and to @flooie for merging into the experimental branch.

> 1. Anything in scripts_archive should just be deleted. I don't know why those exist. If you don't mind nuking those, that'd be great. One less thing to review.

That's fine, I'll merge in the `python38-merger` branch and nuke those scripts.

> 2. You mention mypy. I thought Python 3 had static typing built in?

Indeed it have type hints built in, what mypy does is do static type checking to check that you haven't made mistakes in your typings. What [PEP484](https://www.python.org/dev/peps/pep-0484/) actually is is type *hints*, meaning you can define a Python function like:

```python
def say_hello(name: str) -> str:
    return f"Hello {name}!"
```

But Python won't actually complain if you do `say_hello(17)`. However, mypy will pick it up and tell you that you've made a mistake, which is why it's a really valuable tool for catching all kinds of errors that you'd normally need comprehensive testing for. Also PEP484 gives *gradual* typing, which allows you to slowly add typings to your codebase, so you don't have to do it all at once.

> 3. More cleanup is needed for the old requirements file (and the docker images and ansible scripts that need them, I think).

Indeed, a good point to be would be the Docker Compose tests passing and the requirements all cleaned up.

> I think that's kind of it. Can we trust that with the switch to poetry we will successfully avoid any dependency pain? I'm kind of amazed you cranked out a list of the dozen or so req's with issues.
>
> Are you using some kind of checklist for this?

The things to bear in mind with pip vs. poetry is that pip doesn't actually do any (real) dependency resolution. The juriscraper python-dateutil issue is a good example of this. The way Python dependencies are designed (historically) is that you don't declare dependencies declaratively but imperatively, using a `setup.py`. This means that the dependencies have no guarantees of determinism and they also need to run a Python script to get the list of dependencies. So what pip actually does it just install all the dependencies one after another and whichever version you installed first is the one you have. More info [here](https://dustingram.com/articles/2018/03/05/why-pypi-doesnt-know-dependencies/), [here](https://pip.pypa.io/en/stable/user_guide/#requirements-files) and [here](https://github.com/pypa/pip/issues/988).

The only caveat with poetry is that because most Python dependencies aren't declaratively stated, you need to actually download and run the `setup.py` to see what the dependencies are, which means it can be [really quite slow](https://python-poetry.org/docs/faq/#why-is-the-dependency-resolution-process-slow). This is particularly the case when wildcard versions are specified, like `somedependecy="*"`. (There are workarounds to speed up CI builds.)

I'm not using any kind of checklist, just trying things until they stop breaking 😄

**Comment by mlissner** [comment]
All of this sounds great, thanks @drewsilcock. I think @flooie is working today on unbreaking some tests related to Solr (our search engine). I'll just note that it looks like we need to upgrade scorched to make it support py3, so I think that's a direction he's taking. We also have a vendored library we're using called sunburnt. We've been trying to get rid of that for a while, so this is probably a good opportunity to do that too.

**Comment by drewsilcock** [comment]
I've pushed an update to replace `mock` with `unittest.mock` and remove the `cl/cleanup` directory, although it might make more sense to put those up as a PR against the python38-merger branch?

**Comment by drewsilcock** [comment]
p.s. Python 3.9 is now the latest stable version of Python, as of Monday. (Not that it's particularly important, just thought I'd mention.)

**Comment by mlissner** [comment]
We're incorporating these changes into our weirdly-named 1407-py3-unmerge branch and it has a bunch more changes, so I'm closing this one. Thanks for kicking this off, Drew. Huge deal.

**Pull request closed without merging**
