### PR TITLE
Add info about funnel@recap.email

### PR DESCRIPTION
**Pull request by mlissner**
This is a small update to add info about the new funnel@recap.email trick. Alberto, do you see any reason why this wouldn't work?

### CODE REVIEW

**Comment by mlissner** [comment]
Assuming this passes tests and looks good to you, Alberto, please feel free to merge.

**Comment by mlissner** [comment]
This also fixes #2213.

**Comment by albertisfu** [comment]
Perfect! this looks good. The only thing I think we need to do before is to add a CourtListener user that has assigned the @recap.email:  `funnel@recap.email` so we could process the messages.

**Comment by mlissner** [comment]
> we need to [...] add a CourtListener user that has assigned the @recap.email

I just tweaked this to use archive@recap.email, and I added that to the `recap` user in the system. This is the same user that the extension uses to hit the API, so it's pretty perfect.

**Pull request merged**
