### PR TITLE
refactor(cl): Refactor and Make Code More Pythonic

### PR DESCRIPTION
**Pull request by johnludwigm**
This PR makes the following refactors:

* Removes f from some constant strings
* Removes unneeded imports
* Changes not X in Y to X not in Y
* Makes some parts more Pythonic

### CODE REVIEW

**Comment by mlissner** [comment]
When you're happy with this one, go ahead and request my review and I'll be happy to take a look. (Otherwise, I don't know if it's a work in progress.)

**Comment by johnludwigm** [comment]
@mlissner it's done. I'm not sure how to request a review in GitHub. Please review it :)

**Comment by mlissner** [comment]
It's in the upper right, I think, but I'm on it. 
image

**Comment by mlissner** [comment]
Cool; WFM!

**Comment by johnludwigm** [comment]
@mlissner 
I never had the option. This is all I saw. Do I need to join an org?
image

**Comment by mlissner** [comment]
Ah ha. Github has gotten complicated, that's for sure. Well, just tell me when things are ready and I'll route accordingly. It's probably fine.

**Pull request merged**
