### PR TITLE
fix(settings): Add logic to get the list of INTERNAL_IPS

### PR DESCRIPTION
**Pull request by ERosendo**
This PR adds logic to compute the list of `INTERNAL_IPS` and adds the [django-debug-toolbar](https://github.com/jazzband/django-debug-toolbar) as a dev dependency.

### CODE REVIEW

**Review by mlissner — APPROVED** [review]
Great, thanks.

**Comment by mlissner** [comment]
Shoot, sorry, the poetry file has conflicts. Can you resolve real quick and then merge?

**Comment by ERosendo** [comment]
Sure!

**Comment by ERosendo** [comment]
I tweaked the poetry file. This is set to auto-merge, thank you.

**Pull request merged**
