### PR TITLE
1788 disclosure cleanup

### LINKED ISSUE #1788: Financial Disclosure Release Fix List
We've released the financial disclosure database.  Hooray.  

Now it's time to fix all the bugs we've now found.  

- [x] Select the most recent disclosure instead of the oldest disclosure. 
- [x] Instant search results sometimes start halfwidth before expanding to full width
- [x] People don't like S's when $ are correct  (this was processed once already with a given set of rules)
- [x] Need to decide if 5 judges in the dropdown is still enough.
- [x] transaction_during_reporting_period missing from investment field. ******** Not sure how this happened 
- [x] Should reorder tables to reflect order in disclosure.  Investments (when large) dwarf the rest of the page
- [x] Crowdsourced corrections?

### PR DESCRIPTION
**Pull request by flooie**
Fixes #1788

For some issues (yes I mis labeled the branch name).

Adds spinner for loading financial disclosures.

Drops errant page number links for non investment tables.

https://user-images.githubusercontent.com/6464529/168346031-2a9f2cd8-3541-4ee4-a5bb-4ea1e5c39699.mov

### CODE REVIEW

**Comment by flooie** [comment]
@mlissner I added a simple bump to juriscraper in the hopes to squash one of the annoying sentry Rhode Island errors

**Comment by mlissner** [comment]
Did you consider doing this with font awsome, so we don't need the image? Also...did you forget to check in the image or is there some magic here I don't understand? There's no `src` on your `img` tag either? Confused.

**Comment by flooie** [comment]
Pure css

**Comment by flooie** [comment]
@mlissner - updated with font awesome.

**Comment by mlissner** [comment]
Thanks.

**Pull request merged**
