### PR TITLE
Fix help text for has_inferred_values field in investments of financial disclosures

### PR DESCRIPTION
**Pull request by VolVox99**
The help text had some typos and issues which I fixed.

Also general suggestion: Isn't it kind of strange to have the help text for the fields be embedded in JSON returned from an options request? Wouldn't it be better to also have it displayed on the site in the documentation. That would make it a lot less clearer.

### CODE REVIEW

**Comment by mlissner** [comment]
Thanks for the fix. 

Yeah, it'd be nice if we had these somewhere other than deep in an OPTIONS request. Any interest in making something? I think it'd go a long ways. 

The other thing that probably needs to happen is to break up the mega-long API docs page or improve the way the TOC works or something like that. More examples, probably would help too....

But yeah, pulling these descriptions out of the OPTIONS is probably a big one.

**Comment by VolVox99** [comment]
Potentially later. It shouldn't be too much work though to just parse it from the JSONs that are already present onto the website

**Comment by mlissner** [comment]
Yeah, I was dumbly thinking you'd introspect the Django models, but doing it via a query to the API probably makes a lot more sense. 🤦

**Comment by VolVox99** [comment]
Yeah it's simpler and when the models update then the website would automatically update too.

**Pull request merged**
