### PR TITLE
Issue #2148 - Migrate citation tests to factories

### PR DESCRIPTION
**Pull request by mattdahl**
I was adding some new citation tests related to recent changes in `eyecite` and then decided that it would be best to do this migration first, in re #2148.

f4de4ccb4eebb9d570a4ddc2ce0fe864049a56ed creates a new factory, `CitationWithParentsFactory`, to generate Opinion, OpinionCluster, Docket, Court, etc. objects keyed off of a single `Citation` object. I'm using the `Params` inner class to pass around some variables between the inheriting factories, but I'm not sure if this is the best pattern.

f882951ec49be8f435638f40444ea960dd7ad667 deletes the old citation-specific fixtures and moves their content to factory calls in `citations/tests.py`. The tests themselves are then updated to reference the new objects.

649bffd8080fc1a929dbcb29da70d3bea469060a restores a test for #621 that, as I realized as I was going through things, had been inadvertently deleted in https://github.com/freelawproject/courtlistener/commit/3c8bb688b52054e3afdfb7383bd915b46772579c#diff-5ac43953c02aa13bc64a5393ff430fcda6190f0b9cbaa7f16158daeb1f3ea797L248 (the `9 F. 1` citation).

### CODE REVIEW

**Comment by mlissner** [comment]
Really cool! I do love seeing fixtures getting deleted. Thank you. 

One question: Why use the Params thing? Is it giving us something we don't get otherwise?

**Comment by mattdahl** [comment]
> One question: Why use the Params thing? Is it giving us something we don't get otherwise?

What I was trying to accomplish was being able to call my new `CitationWithParentsFactory()` with some additional parameters that wouldn't be created on the `Citation` model directly, but rather passed down to the sub factories (and sub-sub factories) generated alongside it. For example, I needed to be able to instruct `CourtFactory` to create a `Court` with an `id` of `scotus` (just using a random value, as is the current default, would cause the Solr lookups to fail), so I needed to create a `court_id` parameter and "pass it down" to the `CourtFactory`. Same thing with `date_filed`, which is a keyword argument expected by `OpinionClusterFactory`, but the `CitationFactory` factory will reject it unless it's nested under the `Params` inner class (to signify that it's just a local parameter and not a keyword argument used to instantiate a `Citation` object). This is my first time using factory boy, though, so maybe there is a superior way to achieve this!

**Comment by mattdahl** [comment]
Sure! Imagine we have the `CitationFactory` class as implemented in this PR. With this class I can create standalone `Citation` objects, but what I really want to do is create a `Citation` object and link it to an OpinionCluster, Opinion, Docket, Court, etc. Enter my `CitationWithParentsFactory` class.

As a first pass, I want to use this factory to fill in the `cluster` field on the `Citation` model by creating a `OpinionCluster` object:

```
class CitationWithParentsFactory(CitationFactory):
    cluster = SubFactory(
        "cl.search.factories.OpinionClusterFactoryForCitation",
    )
```

This works fine. However, it would be nice to be able to specify some of the fields that I want set on that linked `OpinionCluster` object, e.g., the `date_filed` field. For example, I would want to be able to call `CitationWithParentsFactory(date_field=MYDATE)` where MYDATE is a datetime object.

My first approach was to implement that like this:
```
class CitationWithParentsFactory(CitationFactory):
    date_filed = Faker("date")
    cluster = SubFactory(
        "cl.search.factories.OpinionClusterFactoryForCitation",
        date_filed=SelfAttribute("..date_filed"),
    )
```

But under that implementation, calling `CitationWithParentsFactory(date_field=MYDATE)` produces an error:
```
TypeError: Citation() got an unexpected keyword argument 'date_filed'
```

The problem is that `CitationWithParentsFactory` thinks that I want to apply the `date_filed` argument to the _Citation_ object, not the sub-factory _OpinionCluster_ object! Factory Boy assumes that all class variables are to be passed as keyword arguments to the `model` set in the `Meta` inner class (here, `Citation`).

To solve this, I need to specify that this `date_filed` variable is intended as just a "local" variable instead, which I do by nesting it under the `Params` inner class:
```
class CitationWithParentsFactory(CitationFactory):
    class Params:
        date_filed = Faker("date")
    cluster = SubFactory(
        "cl.search.factories.OpinionClusterFactoryForCitation",
        date_filed=SelfAttribute("..date_filed"),
    )
```

Now I can call `CitationWithParentsFactory(date_field=MYDATE)` without problem.

The same logic applies to the `court_id` variable, though that one is more complex because it has to be "passed down" through several layers of factories. (`CitationWithParentsFactory` to `DocketParentMixin` to `DocketFactory`.)

Let me know if this makes sense to you. Again, there could be some completely different pattern that I should be using instead!

**Comment by mlissner** [comment]
Got it, thanks for the detailed thoughts. There a couple answers about this problem around, but none that look great. Could you just forgo parent-child approach and make one thing, then use it in the next and the next? It's not as elegant, but it's simpler, which I think counts for something?

**Comment by mattdahl** [comment]
Sorry, now I don't totally follow! Can you say more or write some pseudo code?

**Comment by mlissner** [comment]
Sure, sorry, was being lazy. So let's say that you want to create a citation in a case that's in SCOTUS. To do that, you'd:

 - Use the CourtFactory to create a SCOTUS court.
 - Create a Docket using that court
 - Create an opinion cluster in that docket
 - Create an opinion in the cluster
 - Create a citation to that opinion

In other words, you're just not using the parent factories and you're making each individual object and linking them together. Does that clarify?

**Comment by mattdahl** [comment]
Yes, I think so! Changes in 9ad2f2ba383a37538b025c5f1895022a91140e30.

Now there are only three new factories in this PR, none of which have the Params stuff: `CitationFactory`, `CitationWithParentsFactory` (just extends the former to include a `cluster` field), and `OpinionClusterFactoryWithChildrenAndParents` (because we need a factory that combines creating children, i.e. opinions, and parents, i.e. dockets and courts).

Then, in the tests, I just use those factories (and others) to create the necessary objects "in place" instead.

**Comment by mlissner** [comment]
Woo, that looks cool! Can I trouble you for one more tweak? Can you add citations to the `make_dev_data` command so that they're made by default and available if people want to make them? 

After that, I'll give it one more review, but I don't think there's anything else that caught my eye. This is great!

**Comment by mattdahl** [comment]
Sure, added in [3aeaa5c](https://github.com/freelawproject/courtlistener/pull/2183/commits/3aeaa5ca88db4e11082d499fb049d0e2f3abb9ca). Note: I removed the base `CitationFactory` class (leaving `CitationWithParentsFactory` only) because I realized that the `Citation` model has a not null constraint on the `cluster` field so it would not be possible to create a standalone `Citation` object without a linked cluster anyway.

**Comment by mlissner** [comment]
OK, that's merged, and it'll be automatically deployed to the servers in a few minutes! (I'm really excited about our new auto-deployment system.)

**Pull request merged**
