### PR TITLE
2313 Fix sending welcome email twice for some users.

### PR DESCRIPTION
**Pull request by albertisfu**
This solves the welcome email issue described on #2313 related to time zones.

### CODE REVIEW

**Comment by albertisfu** [comment]
I rebased this with main but seems there's a problem when bumping ipython from 7.31.1 to 8.5.0

**Comment by mlissner** [comment]
That's a bummer. I saw that but assumed there was no way ipython could be causing an issue, and ignored it as a result. Want to revert that and tell dependabot to ignore ipython for a while?

**Comment by albertisfu** [comment]
Yeah of course I'll revert it.

**Comment by albertisfu** [comment]
I've reverted iPython to (7.34.0) the last version before 8.x.x versions and set dependabot to ignore ipython.

**Pull request merged**
