### PR TITLE
docs(all help files): keep menu on screen

### PR DESCRIPTION
**Pull request by dschnelldavis**
On all help pages, affix left menu so it stays on the screen, even as the rest of the page scrolls down.

contributes to issue #2029

### CODE REVIEW

**Comment by mlissner** [comment]
@dschnelldavis, can you share two things for this:

1. A gif of it in action (you can upload it to this PR). In general, screenshots or gifs make this kind of PR much easier to review.

2. A link to the documentation for the feature? I want to learn more! 

Thank you!

**Comment by dschnelldavis** [comment]
I don't know how to make an animated .gif. Here's a .png screen shot of the feature.

Essentially, the menu scrolls with the body a little, until it reaches the top of the page, where it stays fixed as you continue to scroll the rest of the page.

**Comment by dschnelldavis** [comment]
The documentation on this feature is very bad (essentially nonexistant). If you Google "bootstrap 3 fixed side menu", this is the best result:
https://stackoverflow.com/questions/19681895/how-to-create-a-sticky-left-sidebar-menu-using-bootstrap-3

Essentially, you add the following to a div around what you want to fix:
```
data-spy="affix" data-offset-top="165"
```
Which says you want to fix it, and how far to let it scroll before it becomes fixed.

Then you add a little CSS:
```
#toc.affix-top {
  position: static;
  width: 250px;
}

#toc.affix {
  position: fixed;
  top: 0;
  width: 250px;
}
```
Which describes how you want it to act before and after it's fixed.

Once I figured it out, implementing it was easy. The only hard part was tracking down the instructions for what to do. (Hence the importance of good help files. :-)

**Comment by mlissner** [comment]
Hm, so I found this documentation for bootstrap:

https://getbootstrap.com/docs/3.4/javascript/#affix

It references `position:sticky`:

https://developer.mozilla.org/en-US/docs/Web/CSS/position#sticky_positioning

Looking at that and playing a bit, I was able to get the menu to stick without tweaking any JS or HTML, just by adding `position:sticky; top: 0;` to the CSS. 

Did you play with that?

**Comment by dschnelldavis** [comment]
The Bootstrap docs you link to would have been helpful while I was implementing it. Nonetheless, it looks like I did it correctly.

I did play with position:sticky a little, but it didn't work for me, so I must have done something wrong.

The current solution uses the bootstrap recommended html attributes, a little CSS, and no JavaScript. So it's not pure CSS, but it's pretty close. If you'd prefer a 100% CSS solution, we can do that instead, but I don't think it will perform any better than what we've already got.

**Comment by mlissner** [comment]
I think a CSS solution is better. We're going to move off of bootstrap at some point soon, so doing less with it is nice. I got it working by adding `position:sticky; top:0` to the whole sidebar. I feel like it could be done better, but it worked pretty easily?

**Comment by dschnelldavis** [comment]
OK, I removed the Bootstrap specific code, and re-implemented it with pure CSS using `position:sticky; top:0`. Functionally, it works the same as before.

**Comment by mlissner** [comment]
Much nicer! Merging, thank you! @flooie is doing similar work in an upcoming PR, so don't be surprised if the way you implemented this gets tweaked soon.

**Pull request merged**
