### PR TITLE
Migrate V3 RECAP and DOCKETS Search API to ES

### PR DESCRIPTION
**Pull request by albertisfu**
This PR migrates the V3 RECAP and DOCKETS Search API to ES.

It is behind a waffle flag `r-es-search-api-active` (I've created it as disabled in the admin, so it's ready when it's merged).

The result object looks like this:
```
{
            "absolute_url": "/docket/118/6/stewart-v-macomber/",
            "assignedTo": null,
            "assigned_to_id": null,
            "attachment_number": null,
            "caseName": "Stewart v. Macomber",
            "cause": "28:2254 Petition for Writ of Habeas Corpus (State)",
            "court": "District Court, D. New Jersey",
            "court_citation_string": "D.N.J.",
            "court_exact": "njd",
            "court_id": "njd",
            "dateArgued": null,
            "dateFiled": null,
            "dateTerminated": null,
            "description": " ORDER DISMISSING CASE.  Signed by Judge James Donato on 4/3/2024.  (lrc, COURT STAFF) (Filed on 4/3/2024)Any non-CM/ECF Participants have been served by First Class Mail to the addresses of record listed on the Notice of Electronic Filing (NEF)",
            "docketNumber": "3:24-cv-00424",
            "docket_entry_id": 15015,
            "docket_id": 118,
            "document_number": 6,
            "document_type": "PACER Document",
            "entry_date_filed": "2024-04-03T00:00:00-07:00",
            "entry_number": 1,
            "filepath_local": "recap/dev.gov.uscourts.cand.423859/gov.uscourts.cand.423859.6.0.pdf",
            "id": 15016,
            "is_available": true,
            "jurisdictionType": "",
            "juryDemand": "",
            "page_count": 1,
            "referredTo": null,
            "referred_to_id": null,
            "short_description": "",
            "snippet": "                                            Case 3:24-cv-00424-JD Document 6 Filed 04/03/24 Page 1 of 1\n\n\n\n\n                                   1\n\n                                   2\n\n                                   3\n\n                                   4                                  UNITED STATES DISTRICT COURT\n\n                                   5                               NORTHERN DISTRICT OF CALIFORNIA\n\n                                   6\n\n                                   7    ",
            "suitNature": "Habeas Corpus (General)",
            "timestamp": "2024-05-07T10:07:28.404137-07:00"
        }
```

The differences compared to the V3 RECAP Solr version are as follows:

Party fields are not available:
- attorney
- attorney_id
- firm
- firm_id
- party
- party_id

This is because the V3 `RECAP` and `DOCKETS` search types display `RECAPDocuments` instead of `Dockets`, and in ES we don't index parties into the `RECAPDocuments`.

Similarly, the `docket_absolute_url` is not available for the same reason, as it is a field indexed in the Docket document.

In total, the ES V3 `RECAP` and `DOCKETS` types have 7 fewer fields than the Solr version.

### Query Compatibility

In general, all queries from the frontend are compatible with the ES V3 RECAP Search API, except for those that include a party field within an advanced query, for instance:

`q:"firm_id:1245 AND party:(United States)"`

The reason is that party fields are not indexed within RECAPDocuments in ES, so they can't be matched.

However, party filters do work properly. For instance:
```
{
    "type": SEARCH_TYPES.RECAP,
    "party_name": "Defendant Jane Roe",
}
```

will match the right results. This is due to the `has_parent` query we used to solve the party filtering in child documents in #3817.

The `DOCKETS` type works similarly to the `RECAP` Search type. The only difference is that it uses a collapse query to retrieve unique `RECAPDocuments` by `docket_id`, and it also uses a cardinality query to compute the collapsed results, so results over 2,000 are approximated.

I just have a question:

The Solr version uses this method: **`map_to_docket_entry_sorting`**, which maps the `dateFiled` sorting to **`entry_date_filed`** sorting. So, all the queries sorted by **`dateFiled`** are actually processed as **`entry_date_filed`**.

Should we apply the same behavior in the ES version? Currently, it's possible to sort results either by **`dateFiled`** or **`entry_date_filed`** because we have both fields indexed into the `RECAPDocument`

### CODE REVIEW

**Comment by ERosendo** [comment]
> Should we apply the same behavior in the ES version? Currently, it's possible to sort results either by dateFiled or entry_date_filed because we have both fields indexed into the RECAPDocument

I think We should continue using the current approach for RECAP search. This will ensure consistent functionality for the API and existing users, so they won't encounter any changes in how they interact with RECAP search.

**Comment by albertisfu** [comment]
> I think We should continue using the current approach for RECAP search. This will ensure consistent functionality for the API and existing users, so they won't encounter any changes in how they interact with RECAP search.

@ERosendo, you're right. Since the conversion from `dateFiled` to `entry_date_filed` in the current V3 RECAP search API is the expected behavior, it is important to keep it in the ES version as well.

I've applied the method and fixed the tests accordingly.

Let me know if there is anything else needed here.

Thanks!

**Comment by mlissner** [comment]
@ERosendo, if you have already looked at this one, and are happy with it, I'd like to merge it. If you haven't, then it needs to wait until after your current project.

**Comment by ERosendo** [comment]
LGTM :shipit:

**Review by ERosendo — APPROVED** [review]

**Comment by mlissner** [comment]
Auto-merge enabled. Thank you both!

**Pull request merged**
