### PR TITLE
Model for stub cases

### PR DESCRIPTION
**Pull request by quevon24**
This is the model to store the stub cases, it's very simple, all fields are optional because we don't always have the same information (like the westlaw and lexis datasets)

This also contains a very simple tests for object creation, i added the citations string in a specific format because i'll be preprocessing the citations in westlaw and lexis citation merger to use a semicolon to split the citations.

These changes need to be merged in order to update #2621 and #2622

### CODE REVIEW

**Comment by quevon24** [comment]
@mlissner What do you think is the best name for the model?

@flooie has already given me several suggestions for the model's name

1. StubOpinion
2. OpinionStub 
3. OpinionMetadata
4. StubOpinion
5. PartialOpinion

**Comment by mlissner** [comment]
I don't feel like "Stub" is the best word for it, but I can't think of much better. I think my mind has been corrupted by calling it a stub for so many years. I guess if I had to do it, I'd go with `OpinionStub`.

**Comment by quevon24** [comment]
I think that at the moment we no longer need this new model since all the processing of the citation datasets was done locally, we already know which citations to add to which cluster and we already have the command to do it.

Should we close this PR? @mlissner

**Comment by mlissner** [comment]
Yeah, I think that's fine. Let's close it, and we can re-open if we need to. Thanks for revisiting this.

**Pull request closed without merging**
