### PR TITLE
circleci: run more tests during build

### PR DESCRIPTION
**Pull request by davidxia**
* cl/custom_filters/tests.py
* cl/stats/tests.py

### CODE REVIEW

**Comment by davidxia** [comment]
@mlissner

**Comment by mlissner** [comment]
We usually install Redis from source. Do you think it matters if our testing image does it from apt instead? See: https://github.com/freelawproject/courtlistener/wiki/Installing-CourtListener-on-Ubuntu-Linux#installing-redis

**Comment by davidxia** [comment]
I don't think it matters too much right now, but ideally the test and prod envs would be the same. Unrelated: I wish we could run unit tests without redis at all :)

**Comment by mlissner** [comment]
> I wish we could run unit tests without redis at all

Hm, yes, that'd sure be nice. Aspirations!

**Pull request merged**
