### PR TITLE
Update set_vars.yml

### PR DESCRIPTION
**Pull request by smiller171**
related to #572

### CODE REVIEW

**Comment by mlissner** [comment]
The first step of any deployment is to update the code using git, so we already have this script on every machine where we're running Ansible. Seems weird to copy the file to the machine a second time. Is this how Ansible is usually done? 

Thanks for the help! This is a real mess!

**Comment by smiller171** [comment]
After thinking about this a bit more awake, there's a better way. I'll make another commit in a second.

It's also worth pointing out though that it is very strange to have Ansible discover the value of these vars from the system. Normally Ansible would dictate these values.

**Comment by mlissner** [comment]
> It's also worth pointing out though that it is very strange to have Ansible discover the value of these vars from the system. Normally Ansible would dictate these values.

Yeah, hopefully this is a stopgap until we can figure out the Ansible variables system. If you want to make a commit to that end, I think we'd love it.

**Comment by smiller171** [comment]
Let me know what your default values for all of those things are and I can whip up a new PR pretty quick

**Comment by mlissner** [comment]
Here's the settings file in production:

    INSTALL_ROOT='/var/www/courtlistener'
    CL_SOLR_XMX='20G'
    VIRTUALENV_ROOT='/var/www/.virtualenvs/courtlistener'

Something to mention though is that the Django settings also use some of
these settings, so if we put any in Ansible, we'll need to get them into
the Django settings files too somehow. Right now you can see this in action
if you look at cl/settings/05-private.py or cl/settings/10-public.py. The
trick here is that /etc/courtlistener is valid Python and valid bash. Fun!

**Comment by smiller171** [comment]
While I'm looking at this, I've implemented a trick in the past to set the Java heap to half of the available memory by actually looking up the available system memory instead of manually setting it, if you're interested.

My last commit fixes the var lookup. My next PR will assert them instead of doing a lookup

**Comment by smiller171** [comment]
@mlissner Why are you templating elevate.xml instead of just using the copy module? There's no variable expansion in the template.

Also, where are you using `CL_SOLR_XMX`? I don't see that var called anywhere.

**Comment by mlissner** [comment]
@smiller171 Thanks for all this. Some responses:

> While I'm looking at this, I've implemented a trick in the past to set the Java heap to half of the available memory by actually looking up the available system memory instead of manually setting it, if you're interested.

That's interesting, but I think simple is better for us for this. Being able to set it manually has worked well for us.

> Why are you templating elevate.xml instead of just using the copy module? There's no variable expansion in the template.

This is because the elevate.xml file has a stupid example in it that assumes you have string IDs. If you have them set up as integers or similar, it crashes Solr. It's very dumb. Our template simply knocks that out.

> Also, where are you using CL_SOLR_XMX? I don't see that var called anywhere.

This is used by the init/systemd scripts, which you can find in the `scripts` directory.

**Comment by smiller171** [comment]
@mlissner it doesn't seem to be used by any of the existing Ansible stuff though is what I'm saying, so there isn't any reason for it to exist there at this time.

**Comment by mlissner** [comment]
Oh, I gotcha. Yeah, we can pull it out of Ansible. Good point.

**Comment by mlissner** [comment]
Hm, so the changes here didn't work. I guess I don't know what I was expecting, but after this change the script was run using the local path of my ansible playbook applied against the remote machine. Alas, that doesn't work because they're not installed in the same place. I'm going to just hardcode this to /var/www/courtlistener instead of {ansible_playbook}, and everybody will need a symlink.

**Comment by smiller171** [comment]
@mlissner I didn't realize that. I thought {ansible_playbook} evaluated to the working dir on the remote. I'm certain that's doable, just need to do it differently.

**Comment by mlissner** [comment]
Closing per comments in #578.

**Pull request merged**
