### PR TITLE
Add django-elasticsearch-dsl package

### PR DESCRIPTION
**Pull request by mlnewman**
Adding dsl for django elasticsearch

### CODE REVIEW

**Comment by mlissner** [comment]
I rebased on `main`, but luckily it still merged cleanly. Merging!

**Comment by mlnewman** [comment]
Interesting. I created a new branch based off the latest from main and it still required a merge.

**Comment by mlissner** [comment]
Did you pull main before you did a new branch? The other option is that things are just moving fast!

**Comment by mlnewman** [comment]
Yes and it only took 5-10 minutes to load package and commit. Maybe an update was made during that interval.

git checkout main
git pull origin main
git checkout -b es-package
git commit
git push origin es-package

**Pull request merged**
