### PR TITLE
refactor(scraper/commands): Update scraper logging

### PR DESCRIPTION
**Pull request by flooie**
Update backscraper docstrings/typing
Fix bug - overprocessing opinions
Update debug logging for help debugging on server

### CODE REVIEW

**Comment by flooie** [comment]
Converting to draft because of the failed test I was not expecting.

**Comment by flooie** [comment]
This PR tries to resolve #1873 as well.

**Comment by mlissner** [comment]
Hm, just trying to understand this rat's nest myself, since I don't feel like I understand the underlying code. 

It looks like:

1. The `cl_back_scrape_opinions` script runs the `site_yielder()` function. 

1. Site yielder runs `self._download_backwards()` with the parameter from `back_scrape_iterable`. 

1. `download_backwards` sets some attributes (`self.url`, perhaps, or maybe `self.params`), then runs `self._download()` and `self._process_html()`. 

1. Once the content is downloaded and processed by `self._download`, control returns to `site_yielder`, which yields the `Site` object back to the `cl_back_scrape_opinions` script.

1. That script then runs `site.parse()`.

1. `site.parse()` runs:

    ```
        if not self.downloader_executed:
            # Run the downloader if it hasn't been run already
            self.html = self._download()   # <------- UH OH, NOT GOOD! DOUBLE DOWNLOAD.

            # Process the available html (optional)
            self._process_html()
    ```

1. After downloading a second time, `site.parse()` runs each of the attribute getters, like `self.get_docket_numbers()`. Some of those can do downloads to get metadata, but not in the OLC code, so skipping past that hunch.

1. `self.parse()` finishes and control goes back to `cl_back_scrape_opinions`, which calls `self.scrape_court`. That downloads the binary content, checks for dups, and saves stuff to the DB. 

So, I see that `self._download()` is being run twice here (that's the first issue, I think), but I don't yet see how this is true:

> The site object continues to build upon the last scrape and to pass that object into scrape court and enumerate over every opinion every time. This means the total downloaded PDFs would be equivalent to roughly 25,200 downloads.

***Digs deeper***

Ah ha. So `site_yielder()` has the following code:

```
def site_yielder(iterable, mod):

    site = mod.Site()
    for i in iterable:
        try:
            site._download_backwards(i)
            yield site
        except HTTPError as e:
            continue
```

And in OLC's `_process_html`, we have:

```
def _process_html(self):
    for row in self.html.xpath("some-xpath"):
        self.cases.append(
            {
                "date": date,
                "name": name,
                "url": url,
                "summary": summary,
                "docket": "",  # Docket numbers don't appear to exist.
            }
        )
```

So that's the second issue. We don't redefine the site object before iterating it each time, so `self.cases` grows and grows and grows. 

Now, on to your fix, you do two things:

1. You define `site = mod.Site()` before going into the loop. I could be be wrong here, but I don't see how this line does anything most of the time. It looks like it only does something when `site_yielder` doesn't yield anything. In that case, it makes your other addition, `if site.cases` have a variable so it doesn't crash with an `AttributeError`. But we always expect site_yielder to yield something, don't we? So I guess I found this line confusing, but I guess it's necessary to make your other line work all the time.

2. Your second change is to pull `site.scrape_court` out of the for loop. This means it will only get run once, which I guess is OK if we do the append, append, append thing (and use a linear opinion object, which has the cases variable), but that's not really the goal, and I don't *think* it will work if we aren't using the LinearOpinionSite object. 

So, it took me awhile to review this one. A couple things:

1. We should fix the double download error I found (probably by setting `downloader_executed` at some point).
2. We should fix the `site_yielder` so that it creates a new site object on each iteration. Just need to put the `site = mod.site()` inside the loop, I think.
3. We should back out the changes you made, since I think they cause other problems. 
4. This is an unholy rats nest. At some point this whole thing needs a rewrite so bugs like this one aren't so difficult to diagnose and fix. I'm not sure what that rewrite will look like, but this is way too difficult to understand for code that just goes and downloads some stuff.

**Comment by flooie** [comment]
@mlissner 

```
 if not self.downloader_executed:
        # Run the downloader if it hasn't been run already
        self.html = self._download()   # <------- UH OH, NOT GOOD! DOUBLE DOWNLOAD.

        # Process the available html (optional)
        self._process_html()
```

This isn't double downloaded because self.download_executed is set to True when _download() is called.

**Comment by flooie** [comment]
The snowball effect only occurs in the opinionsitelinear scrapers, and can be negated by simply calling self.cases = [] in the download_backwards method in juriscraper.

**Comment by flooie** [comment]
The site.parse() method is still important in both versions but in different ways.  in opinionsitelinear it unwinds the self.cases into the component pieces and in opinion site (regular) it does the parsing required.

**Comment by mlissner** [comment]
Would it be good to do the change to the yielder here though so we don't have to remember to set `self.cases = []` all the time?

**Comment by flooie** [comment]
> Would it be good to do the change to the yielder here though so we don't have to remember to set `self.cases = []` all the time?

Won't that potentially affect a scraper that relies upon cookies and pagination?

**Pull request merged**
