### PR TITLE
Improve transparency with recurring donations

### PR DESCRIPTION
**Pull request by nathreed**
Addresses further discussion in #975, should help make it clear to users that they are making a recurring donation.

### CODE REVIEW

**Comment by nathreed** [comment]
Oops, I did mean to include the docs fix as a separate PR. It seems like once I pushed it to my fork, it got included here for some reason. Anyway, it's just a small change to make it read a bit clearer.

**Comment by mlissner** [comment]
Did you test this? It seems like it'd load with the old text and only get updated to the improved text if somebody click one-time button then clicked the monthly button?

**Comment by nathreed** [comment]
I did test it -- I suppose I've sort of contributed to some non-obvious spaghetti code here. As a result of my last, slightly hacky solution on this page (to select monthly by default and disable all payments except CC), the click() function for the monthly tab gets called on page load. So it loads with the correct text.

**Comment by mlissner** [comment]
Cool. Story checks out. :) We're slowly moving various things to react. I guess this page would be a good candidate if that's your world.

**Pull request merged**
