### PR TITLE
fix(opengraph): missing slash

### PR DESCRIPTION
**Pull request by nathreed**
Followup to #3094 after post-deploy testing revealed a missing `/` in path

### CODE REVIEW

**Review by cweider — APPROVED** [review]

**Comment by nathreed** [comment]
Thanks for merging, and sorry for the oversight. Looks like the deploy failed on this one (https://github.com/freelawproject/courtlistener/actions/runs/6104724210) so it's still broken at the moment.

**Comment by mlissner** [comment]
Thanks. I'm re-running it now.

**Comment by nathreed** [comment]
Re-tested and everything looks good. Thank you @mlissner !

```curl "https://www.courtlistener.com/recap/og-lookup/?file_path=recap/gov.uscourts.gand.319225/gov.uscourts.gand.319225.61.0_1.pdf" | head -n 50
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 27896  100 27896    0     0  23025      0  0:00:01 --:--:--  0:00:01 23307
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta http-equiv="Content-Language" content="en"/>
  <meta name="language" content="en_us"/>
  <meta name="viewport" content="width=device-width,initial-scale=1"/>

  
  <meta name="description" content="Exhibit List - Mark Randall Meadows. (pdw) (Entered: 08/28/2023)
"/>

  
  <link rel="search"
        type="application/opensearchdescription+xml"
        title="CourtListener"
        href="https://storage.courtlistener.com/static/xml/opensearch.d73a7f6aa26e.xml" />

  
  <meta name="application-name" content="CourtListener"/>
  <meta name="msapplication-tooltip" content="Create alerts, search for and browse the latest court opinions."/>
  <meta name="msapplication-starturl" content="https://www.courtlistener.com"/>
  <meta name="msapplication-navbutton-color" content="#6683B7"/>

  
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:creator" content="@freelawproject">
  <meta name="twitter:site" content="@courtlistener">

  
  <meta property="og:type" content="website"/>
  <meta property="og:title" content="Exhibit List &ndash; #61 in The State of Georgia v. Meadows (N.D. Ga., 1:23-cv-03621) – CourtListener.com"/>
  <meta property="og:description"
        content="Exhibit List - Mark Randall Meadows. (pdw) (Entered: 08/28/2023)
">
  <meta property="og:url" content="https://www.courtlistener.com/recap/gov.uscourts.gand.319225/gov.uscourts.gand.319225.61.0_1.pdf"/>
  <meta property="og:site_name" content="CourtListener"/>
  <meta property="og:image"
        content="https://storage.courtlistener.com/recap-thumbnails/gov.uscourts.gand.319225/369992394.thumb.1068.png"/>
   <meta property="og:image:type" content="image/jpeg"/>
   <meta property="twitter:image:alt"
         content="The first page of the document in the linked PDF"/>
   <meta property="og:image:width" content="826"/>
0  <meta property="og:image:height" content="1068"/>
   

  
  <link rel="icon" href="https://storage.courtlistener.com/static/ico/favicon.1ae736eba120.ico">
```

```
<meta property="og:url" content="https://www.courtlistener.com/recap/gov.uscourts.gand.319225/gov.uscourts.gand.319225.61.0_1.pdf"/>
```

**Comment by mlissner** [comment]
My pleasure, thank you. Want to figure out Blue Sky next?? I guess we just need their crawlers User-Agent...

**Pull request merged**
