### PR TITLE
3891 Fixed Dockets source addition

### PR DESCRIPTION
**Pull request by albertisfu**
While investigating issue #3891, I identified different reasons that might have caused the problem. 
I examined the dockets mentioned in issue #3891 within the Dev DB and observed certain patterns that helped in identifying the issues:
[no_recap_dockets_list.csv](https://github.com/freelawproject/courtlistener/files/14808747/no_recap_dockets_list.csv)

### **Outdated `add_recap_source` Method**

Among the non-RECAP dockets, some were identified as having the **`Scraper and Harvard`** source, which was not included in the **`Docket`**'s **`add_opinions_source`** method. Initially, when adding `Harvard` as a source, only `Harvard` was included without considering other non-RECAP Harvard source combinations. Consequently, the RECAP source was not assigned to those dockets.

To address this, I included the missing non-RECAP Harvard sources in the method as follows:

```
SCRAPER_AND_HARVARD,
HARVARD_AND_COLUMBIA,
COLUMBIA_AND_SCRAPER_AND_HARVARD,
IDB_AND_HARVARD,
SCRAPER_AND_IDB_AND_HARVARD,
COLUMBIA_AND_IDB_AND_HARVARD,
COLUMBIA_AND_SCRAPER_AND_IDB_AND_HARVARD,
```
I also reorganized the list of non-RECAP sources used in the `add_recap_source` method into a new list named `NON_RECAP_SOURCES`, placing it in proximity to other source lists in the model. This change facilitates its use in testing, also ensuring any new sources are remembered for updates in both the list and the tests.

### **Overwritten RECAP Source by Scrapers and Opinions Importers**

In the Development Database, I discovered many dockets originally tagged with the RECAP source that had been overwritten by non-RECAP sources.

This issue arose from when we introduced the **`update_or_create_docket`** method, which aimed to check for the existence of related dockets in the database to prevent duplication during scraping or opinions importing. However, if the docket already existed, this method would overwrite its metadata, including the **`source`**. Therefore, if a docket initially added by RECAP was matched during an Opinion import, the source would be replaced by the Opinion's source.

To resolve this, I tweaked the **`update_or_create_docket`** method. Now, if a docket is matched, the incoming Opinion source (either **`COLUMBIA`**, **`HARVARD`**, or **`SCRAPER`**) is added to the original docket source. This required the addition of **`add_opinions_source`**, a new Docket method expecting the incoming Opinion source. It's also required the creation of **`NON_COLUMBIA_SOURCES`**, **`NON_SCRAPER_SOURCES`**, and **`NON_HARVARD_SOURCES`** to prevent multiple additions of the incoming opinion.

### **Outdated `lookup_and_save`**

Another potential cause for missing RECAP source assignments in dockets was found in the **`lookup_and_save`** method, used for merging PACER Free Opinions.

It's source assignment only had:
```
if d.source in [Docket.DEFAULT, Docket.SCRAPER]:
        d.source = Docket.RECAP_AND_SCRAPER
elif d.source == Docket.COLUMBIA:
        d.source = Docket.COLUMBIA_AND_RECAP
elif d.source == Docket.COLUMBIA_AND_SCRAPER:
        d.source = Docket.COLUMBIA_AND_RECAP_AND_SCRAPER
```
It lacked the HARVARD sources and other non-RECAP sources. Maybe given to the nature of these imports, it might be rare to match a docket from other sources like `IDB`. However, assuming that matching and updating a docket with an `IDB` source or a combination is not be problematic. Instead of using custom if-else statement to assign the source, I replaced it by the `add_recap_source` method, which considers all possible scenarios for assigning the RECAP source.

Finally some notes:

- When a docket originally had the `DEFAULT` source and then the RECAP source is added, the resulting source is `RECAP_AND_SCRAPER`. This behaviour is preserved. Just want to confirm the approach applied here: If the original source is `DEFAULT` and then and Opinion source like Scraper, Columbia or Harvard is added, the resulting source is the same Opinion source. This is because `DEFAULT`, representing a value of 0, allows for the addition of any other source, resulting in the same incoming source (Scraper, Columbia, or Harvard).

- Based in the original `add_recap_source` the following sources are ignored:
```
DIRECT_INPUT
DIRECT_INPUT_AND_HARVARD
ANON_2020
ANON_2020_AND_SCRAPER
ANON_2020_AND_HARVARD
ANON_2020_AND_SCRAPER_AND_HARVARD
```
Thus I also ignored them in the new `add_opinions_source` method.  So I want to confirm there is not a scenario where a docket initially added with `DIRECT_INPUT` source could later be updated to include an additional Opinion source like `Harvard` so it should be assigned as `DIRECT_INPUT_AND_HARVARD`?

- Once we agreed on these modifications, we can proceed to correct the source assignment for the affected dockets. It's better to verify their current sources to apply the right adjustments. We can use the following script to get a list of the affected dockets and its current source:

```
import csv
from pathlib import Path
from django.conf import settings
from cl.search.models import Docket
from django.db.models import Count

dockets_with_entries = Docket.objects.exclude(
source__in=Docket.RECAP_SOURCES).annotate(
    de_count=Count('docket_entries')
).filter(de_count__gt=0).values_list("pk", flat=True)

list_ids=list(dockets_with_entries)

dockets_no_recap = Docket.objects.filter(pk__in=list_ids).only("source", "date_created", "date_modified", "court")

media_path = Path(settings.MEDIA_ROOT)
# The directory for storing the CSV
api_directory = media_path / 'non_recap'
api_directory.mkdir(parents=True, exist_ok=True)
csv_file_path = api_directory / 'non_recap_dockets.csv'

with open(csv_file_path, mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(['docket_id', 'source', 'date_created', 'date_modified', 'court'])
    # Save
    for docket in dockets_no_recap.iterator():
        writer.writerow([docket.pk, docket.get_source_display(), docket.date_created, docket.date_modified, docket.court])
```

So I can analyze it and then provide the appropriate script to fix them.

### CODE REVIEW

**Comment by mlissner** [comment]
> Based in the original add_recap_source the following sources are ignored:
> 
>         DIRECT_INPUT
>         DIRECT_INPUT_AND_HARVARD
>         ANON_2020
>         ANON_2020_AND_SCRAPER
>         ANON_2020_AND_HARVARD
>         ANON_2020_AND_SCRAPER_AND_HARVARD
> 
> Thus I also ignored them in the new add_opinions_source method. So I want to confirm there is not a scenario where a docket initially added with DIRECT_INPUT source could later be updated to include an additional Opinion source like Harvard so it should be assigned as DIRECT_INPUT_AND_HARVARD?

I think the add_opinion_source should update these values, actually. It's possible for something to be added via DIRECT_INPUT and then get an additional source added to it. Ditto for ANON_2020, which could be merged with Harvard, resulting in ANON_2020_AND_HARVARD.

**Comment by albertisfu** [comment]
> I think the add_opinion_source should update these values, actually. It's possible for something to be added via DIRECT_INPUT and then get an additional source added to it. Ditto for ANON_2020, which could be merged with Harvard, resulting in ANON_2020_AND_HARVARD.

Sure, just one question: If we consider `DIRECT_INPUT` and `ANON_2020` in `add_opinion_source`, do the possible combinations remain the same?

```
DIRECT_INPUT_AND_HARVARD
ANON_2020_AND_SCRAPER
ANON_2020_AND_HARVARD
ANON_2020_AND_SCRAPER_AND_HARVARD
```

Is it not possible to have combinations like `DIRECT_INPUT_AND_COLUMBIA`, `ANON_2020_AND_COLUMBIA`, or `DIRECT_INPUT_AND_HARVARD_AND_RECAP`?

If so, we would need to add many more combinations to the list of possible sources.

**Comment by albertisfu** [comment]
I've added all possible Docket source combinations based on the base sources.

```
{
    'RECAP': 1,
    'SCRAPER': 2,
    'COLUMBIA': 4,
    'IDB': 8,
    'HARVARD': 16,
    'DIRECT_INPUT': 32,
    'ANON_2020': 64
}
```

To generate the new sources, I used the following script:

```
from itertools import combinations

# Base Sources
sources = {
    'RECAP': 1,
    'SCRAPER': 2,
    'COLUMBIA': 4,
    'IDB': 8,
    'HARVARD': 16,
    'DIRECT_INPUT': 32,
    'ANON_2020': 64
}


def calculate_combinations(sources):
    # Function to calculate source combinations and their numeric values
    combinations_values = {}
    for r in range(1, len(sources) + 1):
        for subset in combinations(sources.keys(), r):
            value = sum(sources[source] for source in subset)
            combinations_values[f"{'_AND_'.join(subset)}"] = value
    return combinations_values

all_docket_sources = {}
for base_source, _ in sources.items():
    all_docket_sources.update(calculate_combinations({k: v for k, v in sources.items()}))

sorted_data = dict(sorted(all_docket_sources.items(), key=lambda item: item[1]))
print("Total Number of Sources:", len(sorted_data))
print("DOCKET Sources: ", sorted_data)

```

This is based on [itertools.combinations](https://docs.python.org/3/library/itertools.html#itertools.combinations) 

which can create combinations based on the input values and the length of the combination. For example:

```
combinations('ABCD', 1) → A B C D
combinations('ABCD', 2) → AB AC AD BC BD CD
...
```
According to docs:
> Elements are treated as unique based on their position, not on their value. So if the input elements are unique, there will be no repeated values in each combination.

In our case the input values are unique and is possible to have combinations from 1 to 7 elements.
For a total of 127 combinations + the DEFAULT (0)

The groups of sources, like **`RECAP_SOURCES`** or **`NON_RECAP_SOURCES`**, are now computed dynamically.

Thus, these groups have been converted to **`classmethods`** instead of static variables, so they should now be called as **`Docket.RECAP_SOURCES()`**.

All new combinations and groups have been moved to **`docket_sources.py`**.

I've updated the code where these sources were being used.

Additionally, I found that in the **`harvard_merge`** and **`columbia_merge`**, there were a couple of custom groups of sources, so I inverted the logic and used **`NON_HARVARD_SOURCES()`** and **`NON_COLUMBIA_SOURCES()`** to avoid creating groups of HARVARD and COLUMBIA sources.

Let me know what you think.

**Review by mlissner — APPROVED** [review]
This looks pretty OK to me, but I'd love to get another set of more careful eyes, so it's off to Eduardo. :)

**Review by ERosendo — APPROVED** [review]
LGTM 👍

**Comment by mlissner** [comment]
Merged! @blancoramiro, when you have a sec, let's deploy this one. It should be exceptionally easy:

1. Shell into the temp pod.
2. Run `./manage.py migrate`
3. Delete the temp pod
4. Re-run the deploy script

This one is really easy because sometimes django makes migrations that don't actually change the DB. When that's the case, you just run the migration so it's marked as run, and that's all it takes.

**Comment by blancoramiro** [comment]
1. Connected to pod `temp-pod-b248f66`.
2. Executed `./manage.py migrate`:
```
Operations to perform:
  Apply all migrations: admin, alerts, api, audio, auth, authtoken, contenttypes, disclosures, donate, favorites, lasc, lib, people_db, pghistory, recap, recap_rss, scrapers, search, sessions, sites, stats, users, visualizations, waffle
Running migrations:
  Applying search.0028_alter_docket_source_noop... OK
  ```
  3. Deleted the pod.
  4. Re-ran the failed job: [24044935558](https://github.com/freelawproject/courtlistener/actions/runs/8760025514/job/24044935558)

**Pull request merged**
