### PR TITLE
Issue 1521 - Integrate eyecite (part 1)

### PR DESCRIPTION
**Pull request by mattdahl**
This is the first of two PRs to address #1521. This one is easy, simply adding `eyecite` as a dependency. The second PR will follow once a new Docker image is built incorporating this change.

Two things:
1. I don't really know our Docker workflow, is there anything else that should go in here?
2. As I mentioned before, the kind of musical chairs that is going on in `poetry.lock` makes me think that I am doing something wrong, but this is just what happens when I run `poetry add`.

### CODE REVIEW

**Comment by mlissner** [comment]
That poetry lock file makes me want to try it myself since poetry is a bit new to me too and they're are some surprising changes in there. (Or maybe @drewsilcock has thoughts too.)

Unfortunately, I'm on vacation this week, so I might not have time for a little bit. You should be able to use the make file to do a build though. From there, I think the docker compose file will pick it up, even if it's not pushed. Would that keep you unblocked until somebody can review?

**Comment by drewsilcock** [comment]
The `poetry.lock` changes seem mostly to be rearranging dependency listing to be in alphabetical order? This seems like it could just be something they changed in a particular version of Poetry - presumably newer versions dump the deps in alphabetical order whereas older ones do it in some other order? Upgrading to most recent Poetry should fix this.

(cf. this commit from Poetry v1.1.4: https://github.com/python-poetry/poetry/commit/f45ec453818aa069b428cb553194411ad440e646)

**Comment by mattdahl** [comment]
@mlissner no worries on the delay, I have other things to work on and there is no rush on this from my perspective. When you do push a new Docker image, though, I think my second PR should be ready to go.

**Comment by mlissner** [comment]
Sorry Matt, this got lost in the shuffle. I'll push a new docker image with this in a sec.

**Comment by mlissner** [comment]
Pushing now. Gonna take awhile (I'm not on my normal connection).

**Pull request merged**
