### PR TITLE
Update bulk script

### PR DESCRIPTION
**Pull request by quevon24**
- Bulk script refactored to make it easier to maintain.
- CourtHouse table added to bulk script.
- OriginatingCourtInformation table added to bulk script. (As i mentioned in issue #3152, OriginatingCourtInformation table is referenced in the docket table.)
- Court appeals_to through table added to bulk script.
- Update court table in bulk script.
- Update bulk data release notes.
- Generate shell script to load bulk data and stream the script to S3. [(Example of generated file here!)](https://gist.github.com/quevon24/9671e4e1dec915176106f1d67082664b)

### CODE REVIEW

**Review by mlissner — CHANGES_REQUESTED** [review]
Code looks good, but can you add something to the release notes, please? 

Also, in the Table of Contents it says "Old Formats" instead of "Release Notes" could you tweak that please?

**Review by mlissner — CHANGES_REQUESTED** [review]
This looks pretty good to me. One thing I'd suggest is that bash has primitive for loops. Did you try using those instead of repeating the same code a bunch of times?

**Comment by quevon24** [comment]
@mlissner I updated the bulk script to reduce a large part of the code to use loops to stream the data to S3, but also to generate the script to load the bulk data

**Review by mlissner — APPROVED** [review]

**Comment by mlissner** [comment]
Thanks Kevin. We missed the bulk generation this month, but we need a howto for this file. What do you think about creating a new discussion topic with a howto and then linking to that from the bulk data documentation? 

Should we wait a month to do that after the bash script has been generated?

**Comment by quevon24** [comment]
Yes, no problem, so people can know how to update the script correctly.

I will continue to investigate to see if something else can be done for the script.

**Comment by mlissner** [comment]
Sorry, what are you investigating regarding the script?

**Comment by quevon24** [comment]
> Sorry, what are you investigating regarding the script?

I mean seeing if the script can be improved even more

**Comment by quevon24** [comment]
> What else did you have in mind? Unless we discover bugs, it seems good to me. Can you set a reminder to do the remaining pieces early next month?

Well, currently we specify the column names, maybe we could just simply copy all columns(I am still thinking the pros and cons of this), which will reduce the size of the arrays in the script.

We could also use the table name as the bz2 filename, e.g. search_docket-2023-08-31.csv.bz2 instead of dockets-2022-08-02.csv.bz2, that also will reduce the variables in the file and reduce the array size.

This:
`declare -a t_4=("search_docket" "$docket_fields" "$dockets_csv_filename")`

will become this:
`declare -a t_4=("search_docket")`

That way we will copy all columns, and use the name of the table as the file name

**Comment by mlissner** [comment]
Gotcha, yeah, those would certainly make the script easier. I think there are column names I excluded though for some reason or other, and, well, we've got the complicated code now, so we might as well stick with it! 

I think we can mark this as done and move to the next thing (but remember to do documentation in a month!)

**Pull request merged**
