### PR TITLE
Make monthly donation the default

### PR DESCRIPTION
**Pull request by nathreed**
Make users more likely to sign up for a recurring contribution. Previously, a one-time contribution was the default.

Addresses #975

### CODE REVIEW

**Comment by nathreed** [comment]
I went ahead and swapped the pills, so now monthly is the default and it's on the left.

**Comment by mlissner** [comment]
This looks OK, but it allows people to submit monthly donations with paypal, check, or cryptocurrency, which shouldn't be possible. Our backend only supports monthly payments by cc?

**Comment by nathreed** [comment]
Hmm, I thought I had checked that case...I will check again tonight and fix.

**Comment by nathreed** [comment]
Finally fixed. Looks like the "unnecessary hack" I removed was the easiest way to make this work properly after all...

**Comment by mlissner** [comment]
Thanks. This is great! I've merged so that I can get it synced with a PR that included a model change yesterday, but it looks good as far as my tests go. Thanks for getting it over the finish line.

**Pull request merged**
