### PR TITLE
Update link to FJC biographies.

### PR DESCRIPTION
**Pull request by jonashleyo**
Quick fix to update links to individual FJC biographies to point to the biography instead of the index to all biographies.

### CODE REVIEW

**Comment by mlissner** [comment]
This looks good to me. We'll test the link when it goes live, but looks good otherwise.

**Comment by mlissner** [comment]
Looks like this isn't quite working. See:

https://www.courtlistener.com/person/45/ronnie-abrams

And:

https://www.courtlistener.com/person/2852/antonin-scalia/

**Comment by jonashleyo** [comment]
Just submitted a pull request for this (see:  [](https://github.com/freelawproject/courtlistener/pull/970)).  The template (view_person.html) should now be able to handle variations in names (i.e. suffix/no suffix, middle name/no middle name).

**Comment by mlissner** [comment]
Thanks, @jonashleyo. FYI, you can avoid needing to write these kinds of messages by mentioning this issue in your commit message. E.g., if your commit message says:

> Fixes #967 

That'll make the commit show up here. AND, what's even cooler is when the commit is merged, that'll automatically close this issue.

**Pull request merged**
