### PR TITLE
Added FVH support to OA and People ES documents

### PR DESCRIPTION
**Pull request by albertisfu**
This PR introduces the required changes to follow the plan outlined in #3670:

- Added `term_vector` support to **`AudioDocumentBase`** and **`PersonBaseDocument`** fields that are highlighted.
- For People, I added a couple of extra fields that are displayed in the frontend and can be highlighted: **`political_affiliation`** and **`school`**.
- Tweaked **`add_es_highlighting`** and **`merge_highlights_into_result`** to ensure highlighting works correctly in the updated tests, while not affecting highlighting in production where the OA and Person document mappings do not yet support FVH.
- Updated tests to reflect the changes in FVH support, mostly related to highlighting whole phrases instead of individual terms.
- No change was required for the parenthetical index here, since it's not using the **`merge_highlights_into_result`** method.

**I noticed a difference when using FVH related to the highlighting of synonym terms.**

If the indexed term is an abbreviation, like **`ptsd`**, and you perform a search by the whole term **`post traumatic stress disorder`**, **`ptsd`** is not highlighted.

This does not affect the match of search results, only the highlighting.

However, if the whole term **`post traumatic stress disorder`** is indexed and you perform a search by **`ptsd`**, in this case, **`post traumatic stress disorder`** is properly highlighted.

The problem seems related to the way term vectors for highlighting are built during indexing. Since synonyms are expanded at search time, they seem to work only in one direction for FVH. We decided not to include synonyms at indexing time to save storage space, and I confirmed that expanding synonyms during indexing solves this issue. I'm not sure if it's worth increasing the index size to support the indexing of abbreviations in both directions.

After this one is merged, we can continue with the process, which is:

Within a pod, rename the **`oral_arguments`**, **`oral_arguments_percolator`**, and **`people_db_index`** indices to their vector versions in **`es_indices.py`**.

`oral_arguments_vectors`, `oral_arguments_percolator_vectors` and `people_db_index_vectors`

Create a new index for each of them:
```
manage.py search_index --create --models people_db.Person
manage.py search_index --create --models audio.Audio
manage.py search_index --create --models  alerts.Alert
```

- Perform a re_index for each index to their new vector version:
```
POST
/_reindex
{
    "max_docs":10000000, #Number of documents we want to copy.
    "source":{
        "index":"oral_arguments"
    },
    "dest":{
        "index":"oral_arguments_vectors"
    }
}
```

- Once this is ready #3721 can be merged.

### CODE REVIEW

**Comment by albertisfu** [comment]
Great. I've added the synonyms filter to **`text_en_splitting_cl`** so synonyms are included at indexing time too.

I removed **`synonyms`** from the exact search time analyzer, **`search_analyzer_exact`**, since according to https://github.com/freelawproject/courtlistener/pull/3492#issuecomment-1867067024 , we don't want to match synonyms during phrase searches.

Now, multi-word synonyms can be highlighted in both ways, either if the abbreviation or the full term is indexed or searched.

---
However, after adding synonyms to **`text_en_splitting_cl`**, I noticed a change in the behavior of how results are matched on queries that contain synonyms. I'll describe it in detail to confirm if this is an acceptable trade-off.

Consider the following synonyms:
**`administrative procedure act, administrative procedures act, apa`**

Previously, a search for **`Administrative`** matched documents containing either **`Administrative`** or **`Administrative procedures act`** but not **`apa`**.

After indexing synonyms, the same search for **`Administrative`** also matches documents containing only **`apa`**. This is because the term **`apa`** is indexed as such:

```
{
    "tokens": [
        {
            "token": "administr",
            "start_offset": 0,
            "end_offset": 3,
            "type": "SYNONYM",
            "position": 0
        },
        {
            "token": "apa",
            "start_offset": 0,
            "end_offset": 3,
            "type": "word",
            "position": 0,
            "positionLength": 5
        },
        {
            "token": "procedur",
            "start_offset": 0,
            "end_offset": 3,
            "type": "SYNONYM",
            "position": 1
        },
        {
            "token": "act",
            "start_offset": 0,
            "end_offset": 3,
            "type": "SYNONYM",
            "position": 2,
            "positionLength": 3
        }
    ]
}
```

So, a search for **`Administrative`** matches the token **`administr`**, which is part of the synonyms expanded from **`apa`**.

If users want to perform a search to match documents that strictly contain **`Administrative`** within the document, they should perform an exact search.

e.g., a search for **`"Administrative"`** will match documents containing either **`Administrative`** or **`Administrative procedures act`** and exclude documents containing **`apa`**.

Similarly, one-way synonyms are partially impacted by this change. Consider:
**`mag => mag, magazine, magistrate`**

A search for **`mag`** continues working as expected, returning documents containing either **`mag`**, **`magazine`**, or **`magistrate`**.

But previously, a search for **`magazine`** only returned results containing **`magazine`**. Now, it also includes results containing **`mag`**.

If only matches that strictly contain **`magazine`** should be returned, users should perform an exact search for **`"magazine"`**.

I've updated the tests accordingly to reflect this new behavior.

---
- Something else to note is that now we're using synonyms at index time, the bidirectional highlighting of multi-word synonyms will only work on synonyms available during the indexing process of the document. If new synonyms are included afterward, it'll be enough to close, update the synonym files, and reopen the index again to make queries match documents that include the new synonym terms (since synonyms are also expanded at search time). However, if they're multi-word synonyms, HL won't work as expected until the document is re-indexed.


- After this is merged. We'll need to update the analyzers that changed for RECAP and Opinions indices.

So the following process will be required:

```
POST /recap_vectors/_close

PUT /recap_vectors/_settings?pretty
{
   "analysis":{
      "analyzer":{
         "text_en_splitting_cl":{
            "type":"custom",
            "tokenizer":"whitespace",
            "filter":[
               "lowercase",
               "synonym_filter",
               "custom_word_delimiter_filter",
               "remove_leading_zeros",
               "english_stop",
               "english_stemmer",
               "remove_duplicates"
            ]
         },
         "search_analyzer_exact":{
            "type":"custom",
            "tokenizer":"whitespace",
            "filter":[
               "lowercase",
               "custom_word_delimiter_filter",
               "remove_leading_zeros",
               "english_stop"
            ]
         }
      }
   }
}

POST /recap_vectors/_open
```


```
POST /opinion_index/_close

PUT /recap_vectors/_settings?pretty
# Same body as recap_vectors

POST /opinion_index/_open
```

This process is not required for the Oral Arguments or People indices, as we will be creating new indices in any case.

**Comment by mlissner** [comment]
So I think we have the choice between:

1. Not using the FVH highlighting.

    We need the performance of FVH, so this is not an option.

2. Having highlighting fail on synonyms:

    > If the indexed term is an abbreviation, like ptsd, and you perform a search by the whole term post traumatic stress disorder, ptsd is not highlighted.
    > 
    > This does not affect the match of search results, only the highlighting.

    This is not great, but at least the correct items are returned, even if you can't quite tell why (b/c no highlighting).

3.  Having multi-term synonyms wrongly returned on single-token queries:

    > After indexing synonyms, the same search for Administrative also matches documents containing only apa. 

    You get extra results when you shouldn't, which is pretty bad.

I think I prefer the second choice because it's better to have the right relevancy instead of perfect highlighting. Can you revert to the correct commit and we'll review with that shortcoming?

**Comment by albertisfu** [comment]
Got it! I've removed the synonyms filter from **`text_en_splitting_cl`**.

I still removed the **`synonym_filter`** from the exact search time analyzer, as we do not want synonyms to match in phrase searches.

I believe this filter is currently used in **`recap_vectors`** and **`opinion_index`**, as these indexes were recently created. Therefore, we would want to update the analyzer in those indexes to ensure the change is applied:

```
POST /recap_vectors/_close

PUT /recap_vectors/_settings?pretty
{
   "analysis":{
      "analyzer":{
         "search_analyzer_exact":{
            "type":"custom",
            "tokenizer":"whitespace",
            "filter":[
               "lowercase",
               "custom_word_delimiter_filter",
               "remove_leading_zeros",
               "english_stop"
            ]
         }
      }
   }
}

POST /recap_vectors/_open
```
```
POST /opinion_index/_close

PUT /recap_vectors/_settings?pretty
# Same body as recap_vectors

POST /opinion_index/_open
```

**Comment by mlissner** [comment]
Great. Off to Eduardo for review. Thank you. :)

**Review by ERosendo — APPROVED** [review]
The code looks good!

**Pull request merged**
