### PR TITLE
Update rest-docs-vlatest.html

### PR DESCRIPTION
**Pull request by karlnicholas**
Issue #486. Add Tips & Tricks section to API docs explaining how to use Java with Let's Encrypt certs.

### CODE REVIEW

**Comment by mlissner** [comment]
Two small things:
 - Do you think you can make this an h2? This will make it fall into the hierarchy better.
 - Do you think you can add a link to the bug where Oracle is working on upgrading their trust store so we can check back on this from time to time and consider excising it?

**Comment by karlnicholas** [comment]
Yes, of course. I thought to put the link to where the issue was being discussed, but forgot at the last minute.

**Comment by mlissner** [comment]
@karlnicholas I think we're still missing the link to Oracle here, but I'd love to get this pulled if we can.

**Comment by karlnicholas** [comment]
Actually, I'm not sure there is an oracle link, but I put a link to the [LetsEncrypt Forum](https://community.letsencrypt.org/t/inclusion-of-isrg-root/9002) that discusses directly.

**Comment by mlissner** [comment]
Sounds good. Thanks for adding this in. It'll get deployed next time we do a release.

**Pull request merged**
