### PR TITLE
feat(workflows): Add build and push workflow

### PR DESCRIPTION
**Pull request by flooie**
Add docker build and push code for main branches if current version is not on docker hub.

### CODE REVIEW

**Review by mlissner — COMMENTED** [review]
Three thoughts:

1. I don't love the duplication between this file and our make file. I'm not sure there's much to do about it, but it's a small concern. There's a good chance Kalki will want to overhaul this soon anyway, so probably not worth a ton of effort.

2. Continuing when something is unsuccessful is weird. A comment to explain seems wise.

3. This action should have a comment in our documentation somewhere, so people know it exists and how it works.

That's all I've got. Assuming this works, please merge after tweaks above that make sense.

**Comment by flooie** [comment]
Im not sure if this will work but it think it will.   But having reflected on it I think I over thought it.  There's no reason we can't just use the makefile to build and push ... right?

**Comment by mlissner** [comment]
I don't know. If you tweak the file to run in this branch, I think it'll run in this PR and you could see?

**Comment by flooie** [comment]
I should've said I tested it in a private repo without the pushing. so it should work just fine.

**Comment by mlissner** [comment]
LGTM!

**Comment by mlissner** [comment]
Yep

**Pull request merged**
