### PR TITLE
941 dockerize binary tools py3

### PR DESCRIPTION
**Pull request by flooie**
941 dockerize binary tools, is a python3 version of dockerize weird binaries and dockerize document tools.  

It adds a new docker container Binary Transformer & Extractors (BTE) to handle document conversions outside of Django.  It accomplishes this by running a separate container that can be called like an API to convert our documents.  

Because much has changed in the conversion to python3, this draft PR does not remove the binaries from the docker image.  This should let us add BTE first, and remove the binaries from the Django and celery images once we feel confident in this new method.  

If this approach is correct, it can be switched out of draft.

### CODE REVIEW

**Comment by flooie** [comment]
This PR suffers from the same CodeQL issue that was previously id'd and is still in review.

**Comment by mlissner** [comment]
What's the PR for the old one? Do we need to close it? 

I haven't looked at this carefully, but yes, smaller is definitely better, so long as we stay organized and make sure to wrap things up. I think if we did this again, I'd want us to do it with a bunch of even smaller steps:

1. Add the BTE to our docker compose
1. Start using the BTE for one kind of task
1. Use it for another
1. And another
1. Until all are transferred over to it
1. Then, finally, clean up the old stuff

As it is, I've got something like 900 lines of code to review and any bugs in any of it will have larger effects than if we had done it in smaller pieces. This is all hindsight of course, and the current approach is fine unless you can easily make it smaller, but we should try to think about shrinking PRs more, so they're easier to apply safely piece by piece. 

I'll review this soon unless you think it's easy to break it down smaller on your end.

**Comment by flooie** [comment]
I closed the previous PRs because they got caught up mostly in the switch to python3.  It would be relatively simple to reverse the removal - like you suggest we do in the future.  I would suspect if we started with audio conversion first that would be the least disruptive process in BTE to the operations of the website.

**Comment by mlissner** [comment]
Sounds good to me.

Le mer. 25 nov. 2020 à 12:55, William Palin <notifications@github.com> a
écrit :

**Comment by flooie** [comment]
Great.

**Comment by flooie** [comment]
@mlissner Unfortunately the rebase to master, as usual, complicated the branch PR.  For that I apologize.  Previous to the rebase of master, the PR was roughly 180 lines and revolves around just a handful of files.  Should I close the PR and just re-commit the small PR from a clean master branch?

**Pull request closed without merging**
