### PR TITLE
feat(search) Added backend ability to sort by document upload date

### PR DESCRIPTION
**Pull request by ikeboy**
Minor tweak on #1260

### CODE REVIEW

**Comment by mlissner** [comment]
Interesting. A few questions:
 - Are these fields indexed in Solr?
 - How are items handled where the field is null?
 - Does the change you make here make it appear in the front end, or just via URL hacks?

**Comment by ikeboy** [comment]
Don't think it's indexed, but the other field isn't indexed either and it worked fine. This just adds it to the back end, so would need to put it in the URL. 

I don't know how it treats null fields.

**Comment by mlissner** [comment]
Sounds good. Can you update the API documentation too, to mention this? There's already a mention in there about random sorting? 

The broken tests are my fault. If you rebase on latest master, they'll go away. Sorry about that.

**Comment by ikeboy** [comment]
I'm not sure why we restrict sorting in the first place. Could it just be opened up and let you search on any valid field? And then you could document the list of fields in the api docs?

**Comment by mlissner** [comment]
Sorry to take so long reviewing this small PR. I've been bogged in a litany of dumb bugs for the past week. I'm finally emerging from them.

> I'm not sure why we restrict sorting in the first place. Could it just be opened up and let you search on any valid field? And then you could document the list of fields in the api docs?

I'd rather be careful about which fields we allow rather than just allow them all, since I think some of them are probably utterly useless as sorting fields and would just clutter the docs, for example. 

As for `date_upload`, I'm sorry to say that I don't think it's even being indexed in Solr, so obviously we can't use it as a sorting field:

```
cl-solr          | 338045337 [qtp653687670-13] ERROR org.apache.solr.core.SolrCore  – org.apache.solr.common.SolrException: sort param field can't be found: date_upload
cl-solr          | 	at org.apache.solr.search.QueryParsing.parseSortSpec(QueryParsing.java:365)
cl-solr          | 	at org.apache.solr.search.QParser.getSort(QParser.java:247)
cl-solr          | 	at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:174)
cl-solr          | 	at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:197)
cl-solr          | 	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:135)
cl-solr          | 	at org.apache.solr.core.SolrCore.execute(SolrCore.java:1976)
cl-solr          | 	at org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:777)
cl-solr          | 	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:418)
cl-solr          | 	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:207)
cl-solr          | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1419)
cl-solr          | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:455)
cl-solr          | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
cl-solr          | 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
cl-solr          | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
cl-solr          | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1075)
cl-solr          | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:384)
cl-solr          | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
cl-solr          | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1009)
cl-solr          | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
cl-solr          | 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
cl-solr          | 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
cl-solr          | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
cl-solr          | 	at org.eclipse.jetty.server.Server.handle(Server.java:368)
cl-solr          | 	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
cl-solr          | 	at org.eclipse.jetty.server.BlockingHttpConnection.handleRequest(BlockingHttpConnection.java:53)
cl-solr          | 	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:942)
cl-solr          | 	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1004)
cl-solr          | 	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:640)
cl-solr          | 	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
cl-solr          | 	at org.eclipse.jetty.server.BlockingHttpConnection.handle(BlockingHttpConnection.java:72)
cl-solr          | 	at org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:264)
cl-solr          | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
cl-solr          | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
cl-solr          | 	at java.lang.Thread.run(Thread.java:748)
cl-solr          | 
```

Did you test this and have it work?

**Comment by ikeboy** [comment]
I didn't test locally, I assumed it would work just like the other field I added last time.

**Comment by mlissner** [comment]
Alas, all fields in the DB aren't necessarily in Solr. Shall we close this one? If you think it's an important field to be able to order by, we could look into adding the data to Solr.

**Comment by ikeboy** [comment]
My use case is I want to find new filings that mention certain keywords. Every couple of days, I search and sort by document date. But I'm missing some, because documents often take a couple of days or more to get uploaded, and so they're sometimes several pages back. To be able to sort in a way that guarantees new stuff matching the sort end up on top is useful.

**Comment by mlissner** [comment]
Would search alerts solve this? https://github.com/freelawproject/courtlistener/issues/612

**Comment by ikeboy** [comment]
I think so. It's only really useful when I want to track something, when I'm just looking stuff up the document entry date sort is fine.

**Comment by mlissner** [comment]
Great. Let's close this one, then and we can focus our energy on the other ticket. It's a tough one, but it'll be really powerful. It won't be a free feature though, to be up front.

**Pull request closed without merging**
