### PR TITLE
fix(parentheticals): exclude short par. from db

### PR DESCRIPTION
**Pull request by varun-iyer**
This commit:
- changes parenthetical descriptiveness grading to completely exclude
  any parenthetical <5 words
- updates tests to verify new behavior

### CODE REVIEW

**Comment by varun-iyer** [comment]
Shoot, I hit Submit instead of Cancel on the gh cli --- didn't mean to open this so soon. Waiting to figure out where best to put a small script to delete non-compliant parentheticals from the DB.

**Comment by varun-iyer** [comment]
Here are a brief few lines to update the existing database to remove parentheticals that are too long:

```python
from cl.search.models import Parentheticals
from cl.citations.filter_parentheticals import is_parenthetical_descriptive

# we can exclude parentheticals with a score greater than .8 since they must have more than 5 words
for p in Parentheticals.objects.filter(score__lt=0.8).iterator():
    if not is_parenthetical_descriptive(p):
      p.delete()
```

**Comment by mlissner** [comment]
OK, this cleanup script is cranking along, flying through results.

**Comment by mlissner** [comment]
Thank you!

**Pull request merged**
