### PR TITLE
Fix misplaced ARG commands in DockerFile

### PR DESCRIPTION
**Pull request by troglodite2**
Build arguments only exist until the next FROM command.

Fixes: #2730

### CODE REVIEW

**Comment by mlissner** [comment]
Can you explain what problem this fixes and how it possibly worked (it did, right?) since according to what you're saying, line 77 shouldn't have worked?

**Comment by troglodite2** [comment]
I added a RUN echo to the Dockerfile
image

Here are the results
image

Here I've added ARG in front of the RUN and FROM lines
image
Here are the results:
image

I am not a docker expert.  I discovered this because I was attempting to use BUILD_ENV on a RUN statement.  You can see that what happens in that case is that the variable is empty.

The question is why was it working on that particular FROM line.  My best guess is that build arguments are always available on certain lines, but it is only the ARG command that brings them into the build environment.

Another way to fix this might be to remove the ARG BUILD_ENV completely, but I think that would just be confusing.  It is self documenting.

**Comment by mlissner** [comment]
Weirdly, your test is failing in a way that indicates your changes made this worse?

**Comment by troglodite2** [comment]
In the comment above, I was working on `main`, not my fixes. I am showing you what the current condition is.

I inserted the RUN above line 77 (only change) to show the value of BUILD_ENV.  I then added an ARG line above that to show that inserting the ARG resolves the issue.

**Comment by mlissner** [comment]
OK, but your test is failing with:

> ERROR: failed to solve: failed to parse stage name "build-": invalid reference format

**Comment by mlissner** [comment]
Fixed via #3130

**Pull request closed without merging**
