### PR TITLE
Elasticsearch connection settings for cluster and SSL support

### PR DESCRIPTION
**Pull request by albertisfu**
This PR modifies the Elasticsearch connection to support a cluster connection, as described in https://github.com/freelawproject/courtlistener/issues/2867#issuecomment-1636640313. This change allows the connection to accept a list of hosts (Elasticsearch nodes that belong to the cluster).

- Security settings were also introduced, along with the enabling of retries and request_timeout.

- New environment variables need to be established in production once the production cluster is operational:

`ELASTICSEARCH_DSL_HOST`: A list of Elasticsearch node hosts, including the port.
`ELASTICSEARCH_USER`: The Elasticsearch user for connecting to the cluster.
`ELASTICSEARCH_PASSWORD`: The Elasticsearch user's password for connecting to the cluster.
`ELASTICSEARCH_CA_CERT`: The certificate authority used to issue the cluster certificates.

Additionally, security has been enabled for the development Elasticsearch instance (cl-es), which now also utilizes an SSL connection.

### CODE REVIEW

**Comment by mlissner** [comment]
This looks good. I fixed a merge conflict and set it to auto-merge.

**Comment by albertisfu** [comment]
Tests on this one are still failing. I think the problem here might be the new ES version is to heavy for being running in CI, doing some tests to figure it out the error.

**Comment by albertisfu** [comment]
Ok, debugging this one I realized that the reason tests were failing was related to the latest version of elasticsearch uses more disk space.

So elasticsearch container was failing to relocate shards:
Screenshot 2023-07-20 at 18 04 26

And the service stopped. 

By default ES has this setting `cluster.routing.allocation.disk.watermark.high` set to 90%  so once disk space is above 90% it tries to move shards to another node.

I confirmed this was the problem by adding a debug action to print the disk space before running tests:

The disk usage is 95%:
Screenshot 2023-07-20 at 18 49 58

So to solve the problem I set` cluster.routing.allocation.disk.threshold_enabled` to `false`.

So for now the problem is fixed and we're using the latest ES version. Once we finishing moving everything to ES and we remove Solr from CI, we'll have more free space.

**Comment by mlissner** [comment]
Great.

**Pull request merged**
