### PR TITLE
refactor(scrapers.utils.get_binary_content): expect site.needs_special_headers

### PR DESCRIPTION
**Pull request by grossir**
Solves #4281

- delete `headers` argument from get_binary_content signature and calls
- handle site.needs_special_headers to decide headers to use

### CODE REVIEW

**Comment by grossir** [comment]
Note that the juriscraper PR needs to be merged first, since it creates the default attribute. If this is merged and deployed before that one, all scrapers will break

**Comment by flooie** [comment]
@grossir - I updated juriscraper so you should be able to update it in this PR to see if it resolves the failing test.

**Comment by grossir** [comment]
@flooie I updated the dependency and it's passing tests now

**Review by flooie — APPROVED** [review]
Simple PR, Looks good to me

**Pull request merged**
