### PR TITLE
add user to dockercompose file

### PR DESCRIPTION
**Pull request by ss108**
This settings change tells Docker to run the Django app as root, which is needed after the `www-data` change to have the container play more nicely with IDEs (in particular, VSCode, which @ERosendo and I use, but I also ran into the same issue trying it with Fleet).

### CODE REVIEW

**Comment by ss108** [comment]
@cweider Can you approve when you get a chance plz

**Comment by ERosendo** [comment]
This works for me. I was able to attach VSCode to the container and used the `pre-commit run --all-files`command.

**Comment by mlissner** [comment]
LGTM, but I'm happy to let Chad make the final determination.

**Review by cweider — APPROVED** [review]

**Comment by ss108** [comment]
@mlissner This is ready to merge

**Comment by mlissner** [comment]
Thanks all!

**Pull request merged**
