### PR TITLE
Make favorites table sortable 

### PR DESCRIPTION
**Pull request by ikeboy**
Adds in the tablesorter jquery plugin and css. The actual code is only a few lines.

### CODE REVIEW

**Comment by mlissner** [comment]
Couple requests:
 - Can you provide a screenshot or two?
 - Can you include the non-minified files adjacent to the minifed ones?

**Comment by ikeboy** [comment]
Screenshot from 2020-08-17 13-00-30

Here's the screenshot. 

Full files have been pushed, I downloaded everything from https://cdnjs.com/libraries/jquery.tablesorter, it's version 2.31.3.

**Comment by mlissner** [comment]
Not gonna lie, looks pretty good! Can we remove sorting on the notes field? Not useful, right? How does the `(none)` value get handled? I assume the dates are working properly?

**Comment by ikeboy** [comment]
None is treated as highest. Dates are sorted correctly. I've excluded notes in the latest commit.

**Comment by mlissner** [comment]
OK, sorry, one last thing I didn't notice before. The various assets should go in the user folder, not the favorites folder. They have more to do with user profiles than they do with favorites (they just happen to be sorting favorites this time, but maybe we'll add them to `/profile/alerts/` next?)

Sorry. I'm pretty sure that's the last thing.

**Comment by ikeboy** [comment]
Moved assets.

**Comment by mlissner** [comment]
Looks great, thank you!

**Pull request merged**
