### PR TITLE
4350 Added a micro-cache to search results

### PR DESCRIPTION
**Pull request by albertisfu**
As requested in #4350, this PR adds a micro-cache to Elasticsearch search results in the frontend for all search types.

The cache key is based on a hash of the request GET parameters, considering all parameters required to identify the request, including the `page`.

The cache is stored in Redis and has a duration of 10 minutes.

Some considerations:

- When the search queries ES to get the results, the query time is shown normally. However, when the results come from the cache, the query time is 0ms.

Screenshot 2024-08-28 at 2 15 40 p m

- The first page of results commonly doesn't include the `page` parameter, which could lead to duplicate caching for the same request (e.g. when using navigation buttons) with and without the `page=1` parameter. To avoid this, requests with no `page` parameter are hashed including `page=1`.
- Also, when using navigation buttons, if the request has an empty `q=""` parameter, it's removed from the GET parameters on the next page. So, when going back to the previous page, an additional request is performed. To avoid this issue, if a request doesn't contain a `q` parameter, it is included as `q=""` to form the hash.
- The cache key also considers that the order of GET parameters might change from request to request. For instance, these two are the same request:
    
    `?type=p&case_name=test&page=1`
    
    `?type=p&page=1&case_name=test`
    
    To avoid creating two different caches for the same request, GET parameters are sorted before creating the hash.
    
- Finally, to enable this micro-cache in production, the following setting must be set to `True`:
    
    `ELASTICSEARCH_MICRO_CACHE_ENABLED`
    
  This setting is useful for two things:

  - The micro-cache is disabled by default for developers.
  - It prevents the micro-cache from interfering with search tests.

Let me know what do you think.

### CODE REVIEW

**Comment by mlissner** [comment]
That all sounds great, thanks Alberto! I'm tempted to make the response time 1ms or something when we use the cache, but whatever, not worth the trouble!

**Comment by albertisfu** [comment]
> I'm tempted to make the response time 1ms or something when we use the cache, but whatever, not worth the trouble!

this is an easy change. I've tweaked it to 1ms

**Review by ERosendo — APPROVED** [review]
LGTM :shipit:

**Comment by mlissner** [comment]
Set for auto-merge! Thank you both!

**Comment by albertisfu** [comment]
Great to enable this in production, we'll need to set  env var `ELASTICSEARCH_MICRO_CACHE_ENABLED` to `True` should we create an issue in infrastructure to do it?

**Pull request merged**
