### PR TITLE
feat(assets): Adds EOY banner

### LINKED ISSUE #4769: Replace GivingTuesday banner with EOY banner on CourtListener
When we take down the Giving Tuesday banner on Wednesday, let's replace it with something like this:

Image

Text: Your support has grown CourtListener to over 10 million opinions, with improved search and API functionality. Help us continue expanding and enhancing access to the law. Donate before the end of 2024 to power free and open legal information for everyone. 

[**Make your DONATION TODAY.**](https://donate.free.law/forms/supportflp)

### PR DESCRIPTION
**Pull request by ERosendo**
This PR fixes #4769 by updating the content of the banner to show our end-of-year message. 

It also tweaks the dismissible template to use a two-row layout, which should make it easier to read.

# Small screens
image

-----
# Medium screens
image

------
# Large screens
image

### CODE REVIEW

**Review by mlissner — APPROVED** [review]
Looks good!!

**Comment by mlissner** [comment]
Oops on both counts! Yes to red and yes to merging when the time is right!

**Comment by ERosendo** [comment]
Got it! I'll update the template

**Comment by mlissner** [comment]
Looks great to me!

**Pull request merged**
