### PR TITLE
2679 Move RT Oral arguments Alerts to ES

### PR DESCRIPTION
**Pull request by albertisfu**
This PR implements Real-time alerts for oral arguments using the Elasticsearch percolator approach.

The new RT alert system works as follows:

- Queries are stored in the same Oral Arguments index. There is a new field called `percolator_query`.
- When an RT Alert (currently only for OA) is saved, the query string is converted to the equivalent Elasticsearch query using `build_es_main_query`. Then, it's stored in the `percolator_query` field in Elasticsearch, and an ID is returned. This ID is stored in the new field `es_id` (index added to this field).
- Additionally, when the alert is removed, the corresponding alert is deleted from Elasticsearch.
- When a new OA object is created, it's automatically indexed in Elasticsearch. We use the `post_index` signal to confirm that the object has been successfully indexed. After that, we retrieve the document that was indexed in Elasticsearch and send it to the percolator.
- The percolator will then return the query ID (IDs) that were triggered by the document.
- Using these IDs, we search for the Alert objects and their associated users. We check if the conditions for sending RT alerts, such as `donated_enough`, are met. If the conditions are met, we proceed to send the alert email and trigger the associated webhooks.
- For each new document that triggers an alert, one email and one webhook are triggered.

Also:
- Fields were added to the second `query_string` mentioned in #2785. This tweak was necessary because, for the percolator to function correctly, all the queries need to specify the fields to search in.
- The `set_results_highlights` method was modified. I noticed that after specifying fields in `query_strings`, the highlights for `field` and `field.exact` could differ, with each highlighting different terms. Consequently, the updated method merges unique highlighted terms instead of selecting a single version to display.
- A test was included to verify that multiple percolated queries used in other tests are correctly triggered by documents.
- There is a failing test after merging the updated branch with the recent changes made to other branches. You will investigate the issue and work on resolving the problem.

@mlissner 
**For now I have the following questions:**

### post_index signal bug
The Django elasticsearch [post_index](https://django-elasticsearch-dsl.readthedocs.io/en/latest/es_index.html#signals) signal is supposed to return the document that was just indexed within the `actions` parameter. However, it's not working as expected. The issue lies with the actions parameter, which is a generator that appears to be consumed before it reaches the signal. As a result, when the signal is triggered, the generator is already empty and the document can't be retrieved.

I solved this problem by overriding the `_prepare_action` document method to store the `document data` in a local attribute before sending the data to ES.

This approach is currently functioning well. However, if the `_prepare_action` method changes in the future, we will also need to update this method accordingly.

Therefore, my question is whether we should open an issue to report this bug. I think I have a couple of ideas to address the issue, and I can describe the problem and propose these ideas in an issue. So the maintainers can evaluate whether it is a viable solution. If so I could also submit a PR to implement the proposed fix.

### Highlighting issue
Highlighting is currently not functioning for these alerts because the percolator only returns the specific alert triggered by a document. So we lose the ability to highlight the matched terms. To handle this problem, we have a couple of options.
  - Perform an additional search query in order to return the document highlighted. 
  - Use an external library to highlight terms based on the search query terms.
Which approach sounds better to you?

### Overwrite argued_after 
Within the `cl_send_alerts` command, the `argued_after` field of the query is overwritten based on the alert rate. For real-time alerts, this parameter is set to 10 days prior to when the command is executed. I believe this is done to prevent the loss of recently created elements that might have an earlier `date_argued` due to delays or other factors.
With the percolator approach, there is no need to adjust this query parameter since documents are percolated as they are indexed, eliminating the risk of losing documents based on their date.

The question is the following, in `cl_send_alerts` the `argued_after` param is overwritten to avoid losing documents, but this tweak also "fix" queries where the user might have set a date in the future (Dec 10, 2023). So these kind of alerts are currently triggered. Should we also overwrite `argued_after` for this reason, before storing it in ES? Or we should just let the query as the user saved it.

### Alert email structure for other rates
Lastly, to implement the next phase involving daily, weekly, and monthly alerts using the percolator, we need to consider the following:
Currently, we send only one email per user at the end of the specified rate, which may contain multiple alerts and many hits for each alert.
In the new approach, to achieve a similar behavior, we would need to store each alert and the document that triggers it until the end of the rate period.
The question is whether we should maintain the same email structure, which includes multiple alerts with different search types and numerous hits for each alert?

### CODE REVIEW

**Comment by albertisfu** [comment]
This PR implements Real-time alerts for oral arguments using the Elasticsearch percolator approach.

The new RT alert system works as follows:

- Queries are stored in the same Oral Arguments index. There is a new field called `percolator_query`.
- When an RT Alert (currently only for OA) is saved, the query string is converted to the equivalent Elasticsearch query using `build_es_main_query`. Then, it's stored in the `percolator_query` field in Elasticsearch, and an ID is returned. This ID is stored in the new field `es_id` (index added to this field).
- Additionally, when the alert is removed, the corresponding alert is deleted from Elasticsearch.
- When a new OA object is created, it's automatically indexed in Elasticsearch. We use the `post_index` signal to confirm that the object has been successfully indexed. After that, we retrieve the document that was indexed in Elasticsearch and send it to the percolator.
- The percolator will then return the query ID (IDs) that were triggered by the document.
- Using these IDs, we search for the Alert objects and their associated users. We check if the conditions for sending RT alerts, such as `donated_enough`, are met. If the conditions are met, we proceed to send the alert email and trigger the associated webhooks.
- For each new document that triggers an alert, one email and one webhook are triggered.


Also:
- Fields were added to the second `query_string` mentioned in #2785. This tweak was necessary because, for the percolator to function correctly, all the queries need to specify the fields to search in.
- The `set_results_highlights` method was modified. I noticed that after specifying fields in `query_strings`, the highlights for `field` and `field.exact` could differ, with each highlighting different terms. Consequently, the updated method merges unique highlighted terms instead of selecting a single version to display.
- A test was included to verify that multiple percolated queries used in other tests are correctly triggered by documents.
- There is a failing test after merging the updated branch with the recent changes made to other branches. You will investigate the issue and work on resolving the problem.

@mlissner 
**For now I have the following questions:**

### post_index signal bug
The Django elasticsearch [post_index](https://django-elasticsearch-dsl.readthedocs.io/en/latest/es_index.html#signals) signal is supposed to return the document that was just indexed within the `actions` parameter. However, it's not working as expected. The issue lies with the actions parameter, which is a generator that appears to be consumed before it reaches the signal. As a result, when the signal is triggered, the generator is already empty and the document can't be retrieved.

I solved this problem by overriding the `_prepare_action` document method to store the `document data` in a local attribute before sending the data to ES.

This approach is currently functioning well. However, if the `_prepare_action` method changes in the future, we will also need to update this method accordingly.

Therefore, my question is whether we should open an issue to report this bug. I think I have a couple of ideas to address the issue, and I can describe the problem and propose these ideas in an issue. So the maintainers can evaluate whether it is a viable solution. If so I could also submit a PR to implement the proposed fix.

### Highlighting issue
Highlighting is currently not functioning for these alerts because the percolator only returns the specific alert triggered by a document. So we lose the ability to highlight the matched terms. To handle this problem, we have a couple of options.
  - Perform an additional search query in order to return the document highlighted. 
  - Use an external library to highlight terms based on the search query terms.
Which approach sounds better to you?

### Overwrite argued_after 
Within the `cl_send_alerts` command, the `argued_after` field of the query is overwritten based on the alert rate. For real-time alerts, this parameter is set to 10 days prior to when the command is executed. I believe this is done to prevent the loss of recently created elements that might have an earlier `date_argued` due to delays or other factors.
With the percolator approach, there is no need to adjust this query parameter since documents are percolated as they are indexed, eliminating the risk of losing documents based on their date.

The question is the following, in `cl_send_alerts` the `argued_after` param is overwritten to avoid losing documents, but this tweak also "fix" queries where the user might have set a date in the future (Dec 10, 2023). So these kind of alerts are currently triggered. Should we also overwrite `argued_after` for this reason, before storing it in ES? Or we should just let the query as the user saved it.

### Alert email structure for other rates
Lastly, to implement the next phase involving daily, weekly, and monthly alerts using the percolator, we need to consider the following:
Currently, we send only one email per user at the end of the specified rate, which may contain multiple alerts and many hits for each alert.
In the new approach, to achieve a similar behavior, we would need to store each alert and the document that triggers it until the end of the rate period.
The question is whether we should maintain the same email structure, which includes multiple alerts with different search types and numerous hits for each alert?

**Comment by albertisfu** [comment]
Some additional toughs about according to our conversation.

- We should shift the percolator to its own index. This would require replicating the OA mapping in this index.
- Consequently, we will end up with two indexes for each model: one index for model documents and another for the percolator.
- I'll analyze and determine if it's practical to move the `Alert` table along with the percolator index. If it's feasible, we should transfer the entire `Alert` model to ES. Otherwise, we'll continue using the `Alert` table in the DB.

**Comment by albertisfu** [comment]
@mlissner some new findings, about this one.

Doing some testing, in order for the percolator to work the percolator index needs the following:

-  The complete document field mapping
- The document must be indexed before percolating the document in order to trigger a query.

In brief, if we'd want to have a different index (let's call it AudioDocumentPercolator) for storing the percolator queries, we'd need to populate this index with identical documents as in the main AudioDocument index.  This essentially leads to data duplication across two different indexes.

Does it remain acceptable to do a separate index for the percolator, despite the resultant data duplication?

**Comment by mlissner** [comment]
> Does it remain acceptable to do a separate index for the percolator, despite the resultant data duplication?

Nope! Turns out that was a bad idea of mine! :) 

Thanks for digging and learning. You're going to be a heck of an ES expert very quickly.

**Comment by albertisfu** [comment]
Continue working on this I discovered an error in my previous comment. I had initially thought that the design of Elasticsearch DSL prevented the use of a different index for the percolator. However, my earlier tests failed not because of the design but because when using two different indexes (one for storing the documents and one for the percolator), the percolator index needs to be refreshed during tests for successful percolator queries.

We now have two distinct indexes: one for OA documents (`AudioDocument`) and one for OA Percolator (`AudioPercolator`). Both require the same mapping definition, but documents will only be stored in `AudioDocument`, while queries will be stored in `AudioPercolator`.

You were correct. This approach is more efficient in terms of performance because the Document and Percolator indexes can be optimized and scaled independently, as suggested in the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-percolate-query.html#how-it-works):

> Given the design of percolation, it often makes sense to use separate indices for the percolate queries and documents being percolated, as opposed to a single index as we do in examples. There are a few benefits to this approach:
> 
> - Because percolate queries contain a different set of fields from the percolated documents, using two separate indices allows for fields to be stored in a denser, more efficient way.
> - Percolate queries do not scale in the same way as other queries, so percolation performance may benefit from using a different index configuration, like the number of primary shards.

**Comment by mlissner** [comment]
Great. Glad to have that sorted and fixed. Do I understand correctly that this PR is still ready for review?

**Comment by albertisfu** [comment]
Oh, no sorry is not ready for review.  I'm still doing some changes related to our talk. Checking if it's possible to move the `Alert` model to ES, spoiler alert, it doesn't seem like a good idea. I'll post the downsides of this approach and introduce an alternative, integrating the `Alert` model to the ES index in a cleaner way and adding just the necessary Alert fields to the ES index. For example, the rate field makes sense to have in the ES index. This adjustment would enable us to filter queries based on the rate, eliminating the need to look through all rate options.

**Comment by albertisfu** [comment]
Ok, this PR is ready for review.

Here are some comments on the latest changes.

- Documents and Percolator indexes have become independent, which will allow for more flexible maintenance and scalability.
- Regarding the use of the Elasticsearch Percolator index as unique storage for Alerts, I did an evaluation to compare the pros and cons of this approach. Here are my findings:
  - Although storing Alerts directly in ES may seem simpler in theory, it could potentially be more complex in practice.
  - Moving Alerts to an ES index as unique storage would require storing all the alerts in a larger index to accommodate `Alerts` for all the rates and object types. Given that the percolator index requires having mapped all the possible fields contained in queries and documents to be percolated, this index would need to include a mapping of all the possible fields from all the models (OA, Opinions, RECAP) that support alerts.
  - Therefore, if more fields need to be supported by the percolator, or if a new model (e.g., RECAP) needs to be added or an existing one updated, this would necessitate reindexing the entire index containing fields for all the models.
  - Having only one large percolator index for all the models might affect the percolator's performance and scalability.
  - Data consistency and durability might be impacted if we use Elasticsearch as primary storage for Alerts, as we won't have the ACID advantages of a traditional database, including transactions.
  - We would lose the advantages of Django ORM for performing queries, handling relations with other models (e.g., `User`), and migrations. We would need to implement our custom methods to handle these actions over the ES index.

- So I think it’s better to continue using the hybrid approach, using Postgres as the primary storage for Alerts and using the ES index solely to store the percolator query and rate.

I've added some enhancements to manage the relationship between the Alert model and the Percolator index.

The general idea is that we would have a Percolator index for each alert type (such as `AudioPercolator`, `OpinionPercolator`, etc.) making these indexes smaller and more efficient than one large index.

In order to perform custom indexing, updating, and deletion (selecting the appropriate Percolator index based on the Alert type), we're using signals to keep Alerts synchronized with the Percolator index. Since the `post_save` and `post_delete` signals are executed within the same transaction (save or delete), if there's an error when saving or deleting the query in ES (for example, if the ES instance goes down), an error will be raised, and the `Alert` instance will remain unchanged, ensuring the Alert object and its associated query in the percolator index are always in sync.

- The es_id field is no longer necessary, as the query is now stored in the percolator index with the same Alert ID, allowing us to keep alerts in sync without issues. If the Alert ID doesn’t exist in the Percolator index, a new document is created; if a document with that ID exists in the Percolator index, it is simply updated.

- I've added highlighting for Search Alerts. After further investigation on how to implement highlights for search alerts, it's possible to obtain highlights directly in the percolator query response. Therefore, we now have highlights for search alerts without needing an additional ES query.

### Next work
I will be adding alerts for other rates, but first, I'll conduct some benchmarking to determine the best approach.

I believe we have some options:

- We could percolate documents in real-time (as in this PR) but for all query rates (not just RT alert queries), allowing us to receive hits for these alerts and store them in a new model according to their rate. At the end of each period (Daily, Weekly, and Monthly), we could run a command to retrieve hits from the database for each rate and distribute them to users.
- Alternatively, we could avoid percolating all query rates in real-time (reducing the number of queries where the document needs to be compared) and only percolate on RT Alert queries (as in this PR). We could then run a command at the end of each rate period, e.g., daily. At the end of the day, we could query to retrieve documents added in the last 24 hours and percolate all of them over daily alerts queries to send out the Alerts. The same could be done for weekly and monthly alerts. - Another hybrid approach could involve percolating daily, weekly, and monthly alerts once a day, sending daily alerts, and storing weekly and monthly alerts to send at the end of the period, instead of doing a larger percolation at the end of the week or month for potentially millions of documents.
In general, the idea is to strike the right balance in terms of what would be most suitable for our specific case regarding distributing the percolator load.

Let me know if you have some toughs about this.

**Comment by mlissner** [comment]
I don't have time to review, but I'll respond to your thoughts. 

1. This all sounds really great. Nice work analyzing highlighting and whether to use an index juts for this. 

2. For the other questions about the other rates, I think the best thing to do is run all alerts all the time, to save hits into the DB somewhere, and to generate emails from the DB on the configured schedule. I like this approach because:

    - it seems like the simplest architecture
    - it prevents bursty alert schedules, where we run a ton of queries against ES at scheduled intervals.
    - it avoids any timezone or other weird problems that could come up by querying documents from the last 24 hours or week or month (question we don't have to answer: "What is a month?").

    I think the one concern about this that you voice is that it could impact performance, but I think the percolator approach will be fast enough not to worry about this too much, and that we should do the simplest approach first, adding complication only if we need to.

**Comment by albertisfu** [comment]
Working on using the percolator for other search alert rates, I realized an additional issue that I'm fixing here: alerts were being sent on object updates as well, not only when the object was indexed for the first time.

To solve this problem, we are now utilizing the Elasticsearch document versioning feature to differentiate between new and updated documents. When a document is indexed for the first time, it receives `_version` `1`, and subsequent updates increment the `_version` counter.

The `_version` is included in the Elasticsearch response when indexing a document, but it is not available using the built-in Django Elasticsearch DSL signals. Therefore, we have deactivated these built-in signals and replaced them with custom signals that allow us to retrieve the document version and only percolate documents that are new.

**Comment by mlissner** [comment]
> Working on using the percolator for other search alert rates, I realized an additional issue that I'm fixing here: alerts were being sent on object updates as well, not only when the object was indexed for the first time.

Very interesting. Why was that happening?

**Comment by mlissner** [comment]
Here we goooo!

**Pull request merged**
