### PR TITLE
Update to actions/checkout@v2-beta

### PR DESCRIPTION
**Pull request by divergentdave**
This will do a shallow clone of the repository, which will speed things up. See also #1059.

### CODE REVIEW

**Comment by mlissner** [comment]
Thank you!

**Comment by mlissner** [comment]
Hm, looks like it's not working: https://github.com/freelawproject/courtlistener/commit/43c564d09cb080f64cdf93ff5e1f87b694feae98/checks?check_suite_id=342182948

**Comment by mlissner** [comment]
The log is particularly not helpful either: 

```
Run actions/checkout@v2-beta
  with:
    repository: freelawproject/courtlistener-solr-server
    ref: origin/master
    token: ***
    clean: true
    fetch-depth: 1
    lfs: false
Added matchers: 'checkout-git'. Problem matchers scan action output for known warning or error strings and report these inline.
Syncing repository: freelawproject/courtlistener-solr-server
Working directory is '/home/runner/work/courtlistener/courtlistener'
/usr/bin/git version
git version 2.23.0
Deleting the contents of '/home/runner/work/courtlistener/courtlistener'
/usr/bin/git init /home/runner/work/courtlistener/courtlistener
Initialized empty Git repository in /home/runner/work/courtlistener/courtlistener/.git/
/usr/bin/git remote add origin https://github.com/freelawproject/courtlistener-solr-server
/usr/bin/git config gc.auto 0
/usr/bin/git config --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
/usr/bin/git config http.https://github.com/.extraheader AUTHORIZATION: basic ***
/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/origin/master*:refs/remotes/origin/origin/master* +refs/tags/origin/master*:refs/tags/origin/master*
##[warning]Git fetch failed with exit code 1. Waiting 3 seconds before trying again.
/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/origin/master*:refs/remotes/origin/origin/master* +refs/tags/origin/master*:refs/tags/origin/master*
##[warning]Git fetch failed with exit code 1. Waiting 4 seconds before trying again.
/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/origin/master*:refs/remotes/origin/origin/master* +refs/tags/origin/master*:refs/tags/origin/master*
```

**Comment by divergentdave** [comment]
Try changing the reference being checked out for the solr server from `origin/master` to `master`, I think that might fix it.

**Comment by mlissner** [comment]
Yeah, that looks like it did it, but it seems like the directories are now changed. Oy:

```

Run cd ../courtlistener-solr-server
  cd ../courtlistener-solr-server
  sudo chown -R :1024 data
  sudo chown -R :1024 solr
  sudo find data -type d -exec chmod g+s {} \;
  sudo find solr -type d -exec chmod g+s {} \;
  sudo find data -type d -exec chmod 775 {} \;
  sudo find solr -type d -exec chmod 775 {} \;
  sudo find data -type f -exec chmod 664 {} \;
  sudo find solr -type f -exec chmod 664 {} \;
  shell: /bin/bash -e {0}
/home/runner/work/_temp/be8130cd-bf63-4e6c-aa55-5625d6271b3b.sh: line 1: cd: ../courtlistener-solr-server: No such file or directory
```

Looks like we just need the `with.path` param now, so trying *that*.

**Comment by mlissner** [comment]
OK, things seem better: https://github.com/freelawproject/courtlistener/commit/337808dbee3fe122081bbdcf6c743a83039dce1e/checks?check_suite_id=342237514

**Pull request merged**
