### PR TITLE
fix(elasticsearch_utils): makes changes to the query generation 

### PR DESCRIPTION
**Pull request by legaltextai**
to ensure exact case name match and order 

this should help prioritize "google v oracle" over "oracle v google" when user searches for the latter. 

fixes: #4366

### CODE REVIEW

**Review by albertisfu — COMMENTED** [review]
@legaltextai this looks good! I just made some changes to address a few issues:

- I created a method called `is_case_name_query` to eliminate duplicated code within the `build_fulltext_query` and `add_fields_boosting` methods.
- I modified the condition in `build_fulltext_query` so that the following `match_phrase`...

    ```
    Q(
        "match_phrase",
        caseName={"query": query_value, "boost": 2, "slop": 1},
    )
    ```
    ...only applies if the query is likely a `caseName` **and** doesn't contain quotation marks `"` since a quoted query implies the user is attempting an exact match, and adding the slop to the `caseName` `match_phrase` would result in matching cases with similar names, even when they're not identical. This is why some tests were failing.
- I also reverted the changes you made to `build_term_query` since this method isn't used for the `caseName` filter. Instead, I applied similar changes to `build_text_filter`, which is the correct method for filtering `caseName`.

I tested these queries on the cluster and they seem to be properly the order of terms in the case name when searching for `google v. oracle`

Text query:

```
{
   "query":{
      "bool":{
         "should":[
            {
               "has_child":{
                  "type":"opinion",
                  "score_mode":"max",
                  "query":{
                     "bool":{
                        "filter":[
                           {
                              "terms":{
                                 "status.raw":[
                                    "Published"
                                 ]
                              }
                           }
                        ],
                        "should":[
                           {
                              "match_phrase":{
                                 "caseName":{
                                    "query":"google v. oracle",
                                    "boost":2,
                                    "slop":1
                                 }
                              }
                           },
                           {
                              "query_string":{
                                 "fields":[
                                    "court",
                                    "court_id",
                                    "citation",
                                    "judge",
                                    "caseNameFull",
                                    "status",
                                    "suitNature",
                                    "attorney",
                                    "procedural_history",
                                    "posture",
                                    "syllabus",
                                    "text^1.0",
                                    "type^1.0",
                                    "caseName.exact^75",
                                    "docketNumber^2.0"
                                 ],
                                 "query":"google AND v. AND oracle",
                                 "quote_field_suffix":".exact",
                                 "default_operator":"AND",
                                 "tie_breaker":0.3,
                                 "fuzziness":2
                              }
                           },
                           {
                              "query_string":{
                                 "fields":[
                                    "court",
                                    "court_id",
                                    "citation",
                                    "judge",
                                    "caseNameFull",
                                    "status",
                                    "suitNature",
                                    "attorney",
                                    "procedural_history",
                                    "posture",
                                    "syllabus",
                                    "text^1.0",
                                    "type^1.0",
                                    "caseName.exact^75",
                                    "docketNumber^2.0"
                                 ],
                                 "query":"google v. oracle",
                                 "quote_field_suffix":".exact",
                                 "default_operator":"AND",
                                 "type":"phrase",
                                 "fuzziness":2
                              }
                           }
                        ],
                        "minimum_should_match":1
                     }
                  },
                  "inner_hits":{
                     "name":"filter_query_inner_opinion",
                     "size":21,
                     "_source":{
                        "excludes":[
                           "text"
                        ]
                     },
                     "highlight":{
                        "fields":{
                           "text":{
                              "type":"fvh",
                              "matched_fields":[
                                 "text",
                                 "text.exact"
                              ],
                              "fragment_size":100,
                              "no_match_size":500,
                              "number_of_fragments":1,
                              "pre_tags":[
                                 "<mark>"
                              ],
                              "post_tags":[
                                 "</mark>"
                              ]
                           }
                        }
                     }
                  }
               }
            },
            {
               "bool":{
                  "filter":[
                     {
                        "terms":{
                           "status.raw":[
                              "Published"
                           ]
                        }
                     },
                     {
                        "match":{
                           "cluster_child":"opinion_cluster"
                        }
                     }
                  ],
                  "should":[
                     {
                        "match_phrase":{
                           "caseName":{
                              "query":"google v. oracle",
                              "boost":2,
                              "slop":1
                           }
                        }
                     },
                     {
                        "query_string":{
                           "fields":[
                              "court",
                              "court_id",
                              "citation",
                              "judge",
                              "caseNameFull",
                              "status",
                              "suitNature",
                              "attorney",
                              "procedural_history",
                              "posture",
                              "syllabus",
                              "caseName.exact^75",
                              "docketNumber^2.0"
                           ],
                           "query":"google AND v. AND oracle",
                           "quote_field_suffix":".exact",
                           "default_operator":"AND",
                           "tie_breaker":0.3,
                           "fuzziness":2
                        }
                     },
                     {
                        "query_string":{
                           "fields":[
                              "court",
                              "court_id",
                              "citation",
                              "judge",
                              "caseNameFull",
                              "status",
                              "suitNature",
                              "attorney",
                              "procedural_history",
                              "posture",
                              "syllabus",
                              "caseName.exact^75",
                              "docketNumber^2.0"
                           ],
                           "query":"google v. oracle",
                           "quote_field_suffix":".exact",
                           "default_operator":"AND",
                           "type":"phrase",
                           "fuzziness":2
                        }
                     }
                  ],
                  "minimum_should_match":1
               }
            }
         ]
      }
   },
   "sort":[
      {
         "_score":{
            "order":"desc"
         }
      }
   ],
   "highlight":{
      "fields":{
         "caseName":{
            "type":"fvh",
            "matched_fields":[
               "caseName",
               "caseName.exact"
            ],
            "fragment_size":0,
            "no_match_size":0,
            "number_of_fragments":0,
            "pre_tags":[
               "<mark>"
            ],
            "post_tags":[
               "</mark>"
            ]
         },
         "citation":{
            "type":"fvh",
            "matched_fields":[
               "citation",
               "citation.exact"
            ],
            "fragment_size":0,
            "no_match_size":0,
            "number_of_fragments":0,
            "pre_tags":[
               "<mark>"
            ],
            "post_tags":[
               "</mark>"
            ]
         },
         "court_citation_string":{
            "type":"fvh",
            "matched_fields":[
               "court_citation_string",
               "court_citation_string.exact"
            ],
            "fragment_size":0,
            "no_match_size":0,
            "number_of_fragments":0,
            "pre_tags":[
               "<mark>"
            ],
            "post_tags":[
               "</mark>"
            ]
         },
         "docketNumber":{
            "type":"fvh",
            "matched_fields":[
               "docketNumber",
               "docketNumber.exact"
            ],
            "fragment_size":0,
            "no_match_size":0,
            "number_of_fragments":0,
            "pre_tags":[
               "<mark>"
            ],
            "post_tags":[
               "</mark>"
            ]
         },
         "suitNature":{
            "type":"fvh",
            "matched_fields":[
               "suitNature",
               "suitNature.exact"
            ],
            "fragment_size":0,
            "no_match_size":0,
            "number_of_fragments":0,
            "pre_tags":[
               "<mark>"
            ],
            "post_tags":[
               "</mark>"
            ]
         }
      }
   },
   "_source":{
      "excludes":[
         
      ]
   }
}
```

Filter:

```
{
   "query":{
      "bool":{
         "should":[
            {
               "has_child":{
                  "type":"opinion",
                  "score_mode":"max",
                  "query":{
                     "bool":{
                        "filter":[
                           {
                              "terms":{
                                 "status.raw":[
                                    "Published"
                                 ]
                              }
                           },
                           {
                              "query_string":{
                                 "query":"google v. oracle",
                                 "fields":[
                                    "caseName.exact"
                                 ],
                                 "default_operator":"AND",
                                 "type":"phrase",
                                 "phrase_slop":"1",
                                 "boost":"2"
                              }
                           }
                        ]
                     }
                  },
                  "inner_hits":{
                     "name":"filter_query_inner_opinion",
                     "size":21,
                     "_source":{
                        "excludes":[
                           "text"
                        ]
                     },
                     "highlight":{
                        "fields":{
                           "text":{
                              "type":"fvh",
                              "matched_fields":[
                                 "text",
                                 "text.exact"
                              ],
                              "fragment_size":100,
                              "no_match_size":500,
                              "number_of_fragments":1,
                              "pre_tags":[
                                 "<mark>"
                              ],
                              "post_tags":[
                                 "</mark>"
                              ]
                           }
                        }
                     }
                  }
               }
            },
            {
               "bool":{
                  "filter":[
                     {
                        "terms":{
                           "status.raw":[
                              "Published"
                           ]
                        }
                     },
                     {
                        "query_string":{
                           "query":"google v. oracle",
                           "fields":[
                              "caseName.exact"
                           ],
                           "default_operator":"AND",
                           "type":"phrase",
                           "phrase_slop":"1",
                           "boost":"2"
                        }
                     },
                     {
                        "match":{
                           "cluster_child":"opinion_cluster"
                        }
                     }
                  ]
               }
            }
         ]
      }
   },
   "sort":[
      {
         "_score":{
            "order":"desc"
         }
      }
   ],
   "highlight":{
      "fields":{
         "caseName":{
            "type":"fvh",
            "matched_fields":[
               "caseName",
               "caseName.exact"
            ],
            "fragment_size":0,
            "no_match_size":0,
            "number_of_fragments":0,
            "pre_tags":[
               "<mark>"
            ],
            "post_tags":[
               "</mark>"
            ]
         },
         "citation":{
            "type":"fvh",
            "matched_fields":[
               "citation",
               "citation.exact"
            ],
            "fragment_size":0,
            "no_match_size":0,
            "number_of_fragments":0,
            "pre_tags":[
               "<mark>"
            ],
            "post_tags":[
               "</mark>"
            ]
         },
         "court_citation_string":{
            "type":"fvh",
            "matched_fields":[
               "court_citation_string",
               "court_citation_string.exact"
            ],
            "fragment_size":0,
            "no_match_size":0,
            "number_of_fragments":0,
            "pre_tags":[
               "<mark>"
            ],
            "post_tags":[
               "</mark>"
            ]
         },
         "docketNumber":{
            "type":"fvh",
            "matched_fields":[
               "docketNumber",
               "docketNumber.exact"
            ],
            "fragment_size":0,
            "no_match_size":0,
            "number_of_fragments":0,
            "pre_tags":[
               "<mark>"
            ],
            "post_tags":[
               "</mark>"
            ]
         },
         "suitNature":{
            "type":"fvh",
            "matched_fields":[
               "suitNature",
               "suitNature.exact"
            ],
            "fragment_size":0,
            "no_match_size":0,
            "number_of_fragments":0,
            "pre_tags":[
               "<mark>"
            ],
            "post_tags":[
               "</mark>"
            ]
         }
      }
   },
   "_source":{
      "excludes":[
         
      ]
   }
}

```
Let me know what do you think.

**Comment by legaltextai** [comment]
Thank you so much Alberto! Does it show as the first result Google v Oracle, Supreme Court case?

**Comment by albertisfu** [comment]
> Thank you so much Alberto! Does it show as the first result Google v Oracle, Supreme Court case?

Yeah that's correct. `Google v Oracle` it's listed first.

**Review by mlissner — APPROVED** [review]

**Comment by mlissner** [comment]
Let see this in the real world. Thanks you guys. Merged and deploying now.

**Pull request merged**
