### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by VolVox99**
Fixed Typo in the help_text of the page_number of investments in financial disclosures.

### CODE REVIEW

**Comment by mlissner** [comment]
Thank you again.

**Comment by VolVox99** [comment]
Welcome. Question: why do these simple changes always fail the checks?

**Comment by mlissner** [comment]
In a word? Crptominers. It used to be that our tests would just run and we could give them environment variables to make them work. Then miners came and Github realized:

 - A PR that lands some miner into a random project's CI pipeline was all too easy
 - Those env vars could also be accessed by the code in PRs

So...no more env vars for people not in the freelawproject workspace, and no CI for new contributors until approved. 

It's all annoying, honestly. :)

It'd be great to get it fixed for folks like you, but I'm pretty sure it's impossible.

**Comment by VolVox99** [comment]
I see. We do live in a society. Thought I was doing something wrong. Thanks
for the explanation.

**Comment by mlissner** [comment]
> I see. We do live in a society.

One can hope.

**Comment by flooie** [comment]
Thanks @VolVox99   ooph @mlissner that one stings

**Pull request merged**
