### PR TITLE
feat(favorites) Show date_last_filing on favorites page and split up …

### LINKED ISSUE #1292: Add date_last_filing field to favorites page
Now that we're checking the date_last_filing field nightly for cases that have been favorited, include the field on the page. This makes it easy if you add a bunch of cases to see which ones have been updated recently. 

Should also split up the page to distinguish appeals from district cases, as we only have this field for district cases. And should add documentation of some sort - it's a nice feature to be able to track a bunch of cases in a less intensive manner than getting emails for all new filings.

### PR DESCRIPTION
**Pull request by ikeboy**
…favorites by type

Closes #1292. 

HTML is a bit messy, I just copied the table 5 times and edited each slightly.

### CODE REVIEW

**Comment by mlissner** [comment]
Hm, this needs some work. We can't have this much repeated code. I can give advice about how to do it better if you want, but I'm not sure you need it. Do you mind taking another approach that's tidier? I'd still expect this to loop over a single variable. The `regroup` tag comes to mind, but I'm sure there are other ways: https://docs.djangoproject.com/en/1.11/ref/templates/builtins/#regroup

**Comment by ikeboy** [comment]
Fixed it up. Had to put the subheading text into python to avoid a bunch of ugly if statements, but I think this is basically as neat as you'll get.

**Comment by mlissner** [comment]
OK, hopefully you don't mind, but when I took a look at this page, I decided I *really* preferred a tabbed interface, and I pulled that together on top of the changes you had.

Can you take a look at this, @ikeboy and let me know what you think? If it passes your review, I'll merge (I don't think you have merge permissions).

**Comment by ikeboy** [comment]
I think there should be a bubble or something showing how many alerts per tab if we're doing it that way. You shouldn't have to click all of them to figure out where your favorites are. 

The only reason I split up appeals cases is because we don't have date_last_filing for those. I suppose having that field just be blank is fine.

**Comment by mlissner** [comment]
OK, counts added. I was thinking it might be good too. Thanks. Tests are failing, but I'll look into them in a sec.

**Comment by ikeboy** [comment]
I had the same two errors in my first version pushed, eventually figured out that I had a hanging `div` tag screwing up the tests. Probably something similar in your case.

**Comment by mlissner** [comment]
I went ahead and merged after adding badges and fixing the tests. Thanks for getting this ball rolling.

**Pull request merged**
