### PR TITLE
Added FVH HL support to RECAP Search

### PR DESCRIPTION
**Pull request by albertisfu**
This PR implements the necessary changes to the ES RECAP index mapping to support the FVH highlighter.

I have added the `term_vector` lists to all fields that are highlighted in the frontend.
Docket Fields:
```
caseName
docketNumber
suitNature
cause
juryDemand
assignedTo
referredTo
court_citation_string
```

RECAP Fields:
```
description
short_description
document_type
plain_text
```

So we can evaluate the impact on the index size if we add term vectors to all the fields that require highlighting. This will help us decide whether to add term vectors to all HL fields or only to those where the FVH represents a significant improvement, especially in fields with large content like **`plain_text`** and **`description`**.

I've made adjustments to the tests to ensure they pass using FVH and also updated the **`merge_highlights_into_result`** method, as the way highlights are returned from FVH has changed.

Additionally, I have introduced the **`ES_HIGHLIGHTER`** setting. This setting will allow the tests to use the FVH highlighter, while in production, the `"plain"` version will continue to be used. This is necessary because using FVH on an index without field vectors, such as the current RECAP index in production, will result in an error.

The plan is to deploy this change without impacting production for now. Then, we can use a maintenance pod, where we will need to rename the RECAP index in **`es_indices.py`**.

e.g:
`recap_index = Index("recap_vectors")`

And then create the new index:
`docker exec -it cl-django python /opt/courtlistener/manage.py search_index --create --models search.Docket`

So the original index is not affected.

Then we'll need to copy the current index content to the new index using the re_index API:
```
POST
/_reindex
{
    "max_docs":10000000, #Number of documents we want to copy.
    "source":{
        "index":"recap"
    },
    "dest":{
        "index":"recap_vectors"
    }
```

We can use:
```
GET
/_cat/indices/recap?v&h=index,store.size
```
To obtain the current index size and then the size of the new index with vectors after the re-indexing is complete.

And we could execute the benchmarks described in: 
https://github.com/freelawproject/courtlistener/issues/3536#issuecomment-1874661680

### CODE REVIEW

**Review by mlissner — APPROVED** [review]
Looks OK at a glance. @ERosendo can you make sure you're happy too, please and we can merge once everybody is happy and convinced that it's safe.

**Comment by ERosendo** [comment]
> @ERosendo can you make sure you're happy too

Sure!

**Review by ERosendo — APPROVED** [review]
The code looks good!

**Comment by albertisfu** [comment]
I removed `short_description` and `text` from the `SEARCH_RECAP_HL_FIELDS` list in Elasticsearch since they're no longer required in ES. But they are required in the Solr version. Therefore, I restored the old `SOLR_RECAP_HL_FIELDS` for its use in Solr.

**Review by ERosendo — APPROVED** [review]

**Review by mlissner — APPROVED** [review]

**Comment by mlissner** [comment]
Looks good to me. Alberto, please merge when you're ready!

**Pull request merged**
