### PR TITLE
assert vars

### PR DESCRIPTION
**Pull request by smiller171**
Need to template settings for the app before merging

### CODE REVIEW

**Comment by smiller171** [comment]
@mlissner This PR is for doing variable assertion instead of discovery. At what point should the correct `INSTALL_ROOT` var be injected into the settings scripts? Planning on just using lineinfile to change how the var is set.

**Comment by mlissner** [comment]
This looks really good (though it conflicts due to the previous PR). The only issue I see here -- and probably this is related to my ansible newness -- how do individual devs set different values for defaults.yml? The nice thing about the current system is that we `/etc/courtlistener` is set up manually on every system, so people can put whatever they want in there without causing issues. With this, any changes will conflict with what's in version control. 

> At what point should the correct INSTALL_ROOT var be injected into the settings scripts? Planning on just using lineinfile to change how the var is set.

I suppose if that's the approach, we should do it at install time, which seems like it will be part of the Vagrant process that's being worked on here: https://github.com/freelawproject/freelawmachine

(Sorry if this is confusing -- we're working to figure this out as we go. The main goals are that it work on dev machines, in production, and in Vagrant. The link above is to the work happening on Vagrant by @voutilad.)

**Comment by smiller171** [comment]
Take some time to read [the docs on variables](http://docs.ansible.com/ansible/playbooks_variables.html). You can pass in variables at runtime with the syntax `ansible-playbook <playbook> -e "var=value"

You can also assign vars to hosts and groups in inventory which is useful for having different groups of servers with different settings that you don't have to pass each time.

**Comment by smiller171** [comment]
Also if you haven't already, go through all of the [intro documentation](http://docs.ansible.com/ansible/intro.html), up until the Configuration File portion. The config file stuff you should skim, but don't worry about Windows, BSD, or networking unless it applies to you.

**Comment by mlissner** [comment]
> Take some time to read the docs on variables. You can pass in variables at runtime with the syntax `ansible-playbook -e "var=value"

That looks extremely promising. I've read a lot of the docs, but hadn't gotten through that part yet. Can you update this PR to merge cleanly, and I'll pull it in?

**Comment by smiller171** [comment]
Do you need this PR the settings scripts first, or would it be fine as-is?

**Comment by mlissner** [comment]
It seems to make sense to include the settings files changes in this PR as well. That'll keep all the changes in one unit.

Thanks for looking into this!

**Comment by smiller171** [comment]
Then I need to know where to put it. There are 4 playbooks and I need to know which it goes in, where relative to other stuff, and which hosts to target. Also, does it need to be templated in the private settings, or just the public settings? If the private settings need to be templated, can you give me a snippet from that file where the var is set currently? The example in the git repo isn't using that var.

**Comment by mlissner** [comment]
The idea you're envisioning is to use Ansible to replace lines in the 10-public.py file, right? I don't think that will work through, because 10-public.py is tracked by git. If it's changed, we won't be able to pull the latest code. 

The hope I had was that we'd be able to dynamically pull the Ansible vars into the settings files instead, sort of like how we pull the settings in from /etc/courtlistener currently.

**Comment by mlissner** [comment]
I'm about to update the settings files so that INSTALL_ROOT is no longer a variable that exists. Instead it will just be hardcoded as /var/www/courtlistener, and if people don't like that, they can set up a symlink. It simplifies enough things that I think I can live with it unless there's a better way forward.

**Comment by smiller171** [comment]
@mlissner honestly the best thing would be to convert ALL of your configuration management stuff, including 10-public.py, to Ansible instead.

**Comment by smiller171** [comment]
Failing that, 10-public.py is currently getting values from /etc/courtlistener, right? Ansible should be used to template that.

**Comment by mlissner** [comment]
Closing per comments in #578.

**Pull request closed without merging**
