### PR TITLE
feat(urls pattern): Allow url for dockets/opinions view w/o name slug

### PR DESCRIPTION
**Pull request by flooie**
Two small tweaks to the url pattern for view_opinions and view_dockets

This allows loading the document without a superfluously slug attached.

### CODE REVIEW

**Comment by mlissner** [comment]
This seems fine. Can you add one small test somewhere to make sure that it is supported in the future? I think there are some similar tests for loading simple pages somewhere. All I'd want to do is make sure that you can load it as either:

    /docket/23/

or

    /docket/23/slug/

We may have to revert this someday because the slugs can be used to provide a measure of security against scrapers, but I'm OK with it for the moment. There was a time not too long ago where an aggressive scraper was going page by page and the fix was to make the (correct) slug a required argument.

**Comment by flooie** [comment]
Sounds good.  - what about allowing /docket/23/ to redirect to the right url - and you could turn off the redirect in case of a spammer again?

**Comment by mlissner** [comment]
Sounds good to me, yep.

**Comment by mlissner** [comment]
Woo, lots of failing checks, but more importantly, why does this PR have stuff from the other one???

**Comment by flooie** [comment]
oh yeah

**Comment by mlissner** [comment]
@flooie I'm closing this one. Let's create a new clean PR for this change instead.

**Comment by flooie** [comment]
im down.

**Pull request closed without merging**
