### PR TITLE
feat(bulk_script): Add people_db_person_race

### PR DESCRIPTION
**Pull request by dghopkins**
Add the people_db_person_race table to the list of tables to be exported

### CODE REVIEW

**Comment by mlissner** [comment]
Thanks for this, @dghopkins! We missed the generation of the bulk files this month, but once it's done and merged I think I can do a one-off run of this table for you.

@quevon24, can you please review and merge if it looks good?

**Comment by quevon24** [comment]
@mlissner everything looks good

**Comment by dghopkins** [comment]
@mlissner If you can do a one-off run of the person-race table, that would be great!

**Comment by mlissner** [comment]
Great. The code is merged and I did the one-off data generation. It's here:

https://storage.courtlistener.com/bulk-data/people-db-races-2023-10-31.csv.bz2

Thanks for the helpful contribution!

**Pull request merged**
