### PR TITLE
Issue 1003: Docket Alert should check if document has been uploaded vs. going directly to buy on Pacer

### PR DESCRIPTION
**Pull request by lkj19zpdiDDe**
…e document has been uploaded after the email is generated which is the case most of the time

### CODE REVIEW

**Comment by mlissner** [comment]
This is an oft requested feature and I really appreciate you taking a stab at it. I think the *right* way to do this is to use a URL in the emails that just does the right thing. That is, if you click it and we have the document, we show it. If you click it and we don't, we redirect you. I'm not sure if our current URLs could/should be tweaked into doing this, but it could work. Want to do a little research and propose a spec for how this might work?

**Comment by lkj19zpdiDDe** [comment]
Sure, happy to review, document a proposed approach, and then work on it.

**Comment by mlissner** [comment]
@lkj19zpdiDDe Do you still hope to continue this feature?

**Comment by lkj19zpdiDDe** [comment]
I do but have been busy with other task. (The untested changes are sitting locally...) If someone else is interested or this is more urgent, let me know.

**Pull request closed without merging**
