### PR TITLE
Fix for nebraska scraping

### PR DESCRIPTION
**Pull request by quevon24**
As i mentioned in issue #1452 the problem with nebraska opinion files is that they are updating them causing the timestamp to be updated in pdf, causing the generated sha to not match the one stored in CL opinions.

The solution I propose is really simple, they are updating the pdf files but the download url is still the same, for example, this opinion https://www.courtlistener.com/opinion/6905720/schaaf-v-schaaf/ is duplicated 26 times, the first timestamp is from 07/22/2022 09:05 AM CDT and the last is from 10/14/2022 09:07 AM CDT but the download url is always the same: https://www.nebraska.gov/apps-courts-epub/public/viewOpinion?docId=N00008736PUB

What makes this fix is that when the scrapper for Nebraska is run, it will use the download_url as the lookup field instead of sha field which can easily change even if they just update the timestamp.

This is really simple, but does the job, and in case of having a similar situation to the one with nebraska, we just need to add the court_str to the exception list.

### CODE REVIEW

**Comment by flooie** [comment]
I'd like to get @mlissner thoughts on this - but I think we shouldn't modify the cl scrape opinion for a one off court - if we can resolve this by tightening up the citation formatting in reporters-db

**Comment by flooie** [comment]
@quevon24, I actually on second thought, wonder if this should be a default check just in general and not specific to Nebraska.

**Comment by mlissner** [comment]
> I wonder if this should be a default check just in general and not specific to Nebraska.

The balance here is between opinions that are legitimately being corrected by the court and opinions that are  getting new sha1 hashes every time you download them. 

If we add a check like this by default, we'll stop getting legitimate updates from the court, which is not so great. I think I like @quevon24's fix for that reason. We maintain our ability to get updated opinions, except in dumb jurisdictions where they generate PDFs. 

A bigger fix, I suppose, would be to diff the contents after each addition and make some sort of clever guess about whether they fixed something or just tweaked a timestamp, but that is hard because our text extraction is asynchronous. 

And the biggest fix, of course, is to do better things in the UI when we identify duplicated opinions. It wouldn't be such a big deal to have these duplicates if the UI coalesced them together in all relevant places. Then, people could see that there were "29 versions of this opinion" or whatever, and then look at the others. Still, this bug would be annoying, but we'd push analysis of it to users, who can make their own decisions about it. We'll get that working next year, I think. I don't think we'll have much choice pretty soon.

In the meantime, I think the simple, surgical solution just for NEB is fine?

**Comment by flooie** [comment]
I think it would be perfectly reasonable if this is a problem in the future to remove the annotation stamp - I think it would be easy enough to do - and maybe something we want to get good at - if we eventually want to clean up the footers and headers that destroy our HTML, regardless this is good.  

@quevon24 I would of course love a test but its small enough of a change I think.

**Pull request merged**
