### PR TITLE
4576 Store API search queries

### PR DESCRIPTION
**Pull request by albertisfu**
As requested in #4576, this PR adds support for storing queries from the Search API. It applies to the following scenarios:

- V3 Search API running on Solr (endpoints still run on Solr)
- V3 Search API running on Elasticsearch (endpoints running on Elasticsearch, such as People, and future endpoints once we fully transition V3 to Elasticsearch)
- V4 Search API

Note that `hit_cache` will always be False on API Search queries. Since we don't have a cache implemented for the API.

For the V3 API running on Elasticsearch, I added error handling since we weren’t previously catching Elasticsearch errors. This allows us to store and flag failed queries. Error messages and status codes remain consistent with those in V4 of the Search API.

Additional changes:

- Added `SearchQueryAdmin` with cursor pagination.
- Removed the use of the `ceil` method when storing `query_time`, as times are always integers (milliseconds).

### CODE REVIEW

**Review by mlissner — APPROVED** [review]
LGTM, thank you!

**Comment by mlissner** [comment]
@legaltextai, note that we'll start saving API queries now too, so you can segment that way if you need to starting in about 20 minutes.

**Comment by albertisfu** [comment]
It seems that the deployment is failing. I think it's due to unapplied no-op migration from:

https://github.com/freelawproject/courtlistener/pull/4572

**Comment by mlissner** [comment]
I'm on it. :)

**Pull request merged**
