### PR TITLE
2672 upgrade current tests for oral argument search

### PR DESCRIPTION
**Pull request by albertisfu**
This PR updates and increases the number of Oral Argument search tests to ensure that we can replicate the search behavior when moving the search to Elasticsearch or tracking search changes.

Some of the new tests are:

- Ordering by date_argued `asc` or `desc`
- Ordering by relevance with one or multiple search terms and different terms order.
- Search within the `text` for multiple available terms
- Test highlighted results 
- Filter by `caseName`
- Filter by `jurisdiction`
- Filter by `date_argued`
- Filter by `Judge`
- Combine filtering and text query for multiple fields and terms.
- Advanced search with multiple expressions like: `NOT`, `OR`, `AND` grouped expressions `(OR) AND` and fields like `docket_id`, `id`, `court_id`, `panel_ids`, `dateArgued`, `caseName`, `judge`, and combined expressions.
- Latest oral arguments on the Home page.

In #2732 we'll be moving Oral Argument search to elasticsearch based on these tests.

This PR should be merged first into #2685 before merging #2685 into #2136, according to the dependency order.

### CODE REVIEW

**Review by mlissner — COMMENTED** [review]
This looks really good. Two thoughts. One, it seems light on API tests. Are there more you could add there, that would give us more confidence? I could almost see it added as an additional assertion to several of these tests.

Two, how close are we to ditching the audio fixture?

**Comment by albertisfu** [comment]
I've added additional assertions to the tests in order to test the Oral Arguments API search.
Also removed the audio fixture.

Let me know what you think.

**Comment by albertisfu** [comment]
Something to keep in mind related to this PR update is that some tests were transformed to be `async` on main. Those tests were removed here, since in this PR we moved OA test to its own class and added more tests (test in this class are still Solr Tests, in the next PR they are transformed to ES tests).
So now those tests are not async anymore. I think for now it’s ok, if we change them here it’ll make more complex track changes on the following PRs. 

However once we reach the last PR where OA tests were modified, we should change all the test in order to be async where required.

**Comment by mlissner** [comment]
It's all happening...

**Pull request merged**
