### PR TITLE
feat(filters): Add filter for harvard opinions

### PR DESCRIPTION
**Pull request by flooie**
Add filter for harvard xml opinions. 
Filter simply overwrites the hard coded length to 100% to keep images from extending beyond the scope of the opinions.

See **Before**
Screen Shot 2022-07-29 at 7 11 32 AM

And **after**
Screen Shot 2022-07-29 at 7 11 20 AM

### CODE REVIEW

**Comment by flooie** [comment]
PR Fix for #1838

**Comment by flooie** [comment]
@mlissner just wanted to re-up this for your review.

**Comment by mlissner** [comment]
Hm, a couple thoughts:

 - Did you look at how this is handled in case.law? They handle it with some CSS that does:

    ```
    .casebody img {
      max-width: 100%;
      height: auto;
    }
    ```

 - I don't love doing this as a filter. I'd rather do it during ingestion or as a CSS tweak, I think. Why do you prefer the filter? 

 - I didn't test your approach, but I suspect it squishes the image instead of scaling it. (My approach to CSS did the same until I grabbed the stuff of case.law.)

**Comment by flooie** [comment]
No you're right.  thats probably the way to go... ill adjust this.

**Comment by mlissner** [comment]
Fixed via https://github.com/freelawproject/courtlistener/pull/2343

**Pull request closed without merging**
