### PR TITLE
build(deps): update django-rest-framework for CSP

### PR DESCRIPTION
**Pull request by cweider**
`django-rest-framework` has recieved several patches for CSP compatibility, but unfortunately these are not included in the latest release (3.14.0) and a new release cannot be expected for a while.

As such, we must replace the semantically versioned PyPI reference with a reference to the latest commit on the master branch of the package's Git Repository (do not use `master` since it could change in unexpected and incompatible ways).

Fixes: #3020

### CODE REVIEW

**Comment by mlissner** [comment]
Not my favorite merge, but necessary so we can have secure CSP headers. Thank you. Set for auto-merge.

**Comment by cweider** [comment]
I should add, the log of commits since the latest release is at [encode/django-rest-framework@3.14.0...40eccb0](https://github.com/encode/django-rest-framework/compare/3.14.0...40eccb0).

**Comment by cweider** [comment]
Ok, so the latest version of the `django-rest-framework` is _not_ a drop-in replacement. Updated change to use an earlier commit that contains the relevant CSP changes and none of the changes (affecting permissions and HTTP status codes) causing issues for tests.

Also note the addition of the `inflection` package, which unfortunately became a hard requirement for users of the built-in schema generation. Switching to `drf-spectacular` is looking more compelling!

**Comment by cweider** [comment]
And the change has immaterial change to the generated spec – `listPersons` getting replaced by `listPeople`. Note: these IDs should be unique! `disclosure-typeahead` operation base name needs to be something like `DisclosureTypeaheadPerson` – a task for later.

```
% diff -u <(curl -s https://www.courtlistener.com/api/swagger/) <(curl -s http://localhost:8000/api/swagger/)
--- /dev/fd/11	2023-08-23 10:14:05
+++ /dev/fd/12	2023-08-23 10:14:05
@@ -6722,7 +6722,7 @@
     },
     "https://www.courtlistener.com/api/rest/v3/api/rest/{version}/people/": {
       "get": {
-        "operationId": "listPersons",
+        "operationId": "listPeople",
         "description": "",
         "parameters": [
           {
@@ -9060,7 +9060,7 @@
     },
     "https://www.courtlistener.com/api/rest/v3/api/rest/{version}/disclosure-typeahead/": {
       "get": {
-        "operationId": "listPersons",
+        "operationId": "listPeople",
         "description": "",
         "parameters": [
           {
```

**Comment by mlissner** [comment]
I'm assuming that spec change is a fix, right, so that's good. Thanks for doing the diff. 

The rest sounds good to me. Lucky that we were able to get the CRF fixes without the other stuff.

Once again I rebased and this is set for auto-merge once tests pass.

**Review by mlissner — APPROVED** [review]

**Comment by mlissner** [comment]
Sigh. Should have known it'd have conflicts. Mind regenerating the lock file? I should have done the dependabot stuff second, sorry.

**Pull request merged**
