### PR TITLE
2473 Fixes scraper and Harvard id source

### PR DESCRIPTION
**Pull request by albertisfu**
As described in #2473, this fixes the `SCRAPER_AND_HARVARD` `source` from 17 to 18.

So once this is merged we could add the `HARVARD_AND_RECAP` 17 source, so that we could start assigning this source for dockets added by Harvard and updated by RECAP.

As Bill wrote, seems there are no rows using the 17 source right now according to the code. 
But just in case:
```
UPDATE public.search_docket
SET source=18
WHERE source=17;
```

### CODE REVIEW

**Comment by albertisfu** [comment]
mmm seems that `pre-commit` is broken, checking it...

**Comment by albertisfu** [comment]
The pre-commit fix is in https://github.com/freelawproject/courtlistener/pull/2503

**Comment by mlissner** [comment]
Sorry, I'm dense, but why not do this now: 
> So once this is merged we could add the HARVARD_AND_RECAP 17 source, so that we could start assigning this source for dockets added by Harvard and updated by RECAP.

**Comment by albertisfu** [comment]
Yeah, I just wanted to be sure there are no `SCRAPER_AND_HARVARD` rows to update before,  otherwise, you're right, we can start adding also `HARVARD_AND_RECAP` from now, so I added it in this PR.

**Pull request merged**
