### PR TITLE
3257 Added "See full docket for details" button on docket_id query

### PR DESCRIPTION
**Pull request by albertisfu**
As described in #3257 when filtering a single docket using the `docket_id` we need to show a `XYZ total filings. See full docket for details` button if the Case has more entries than the limit inner hits limit in a result (100). 

I've added this button linked to the docket detail page,  it looks like this:

Screenshot 2023-10-27 at 14 28 09

### CODE REVIEW

**Review by mlissner — APPROVED** [review]
Looks about right to me. @ERosendo, want to give it a look?

**Comment by ERosendo** [comment]
Sure!

**Comment by albertisfu** [comment]
I've decreased `VIEW_MORE_CHILD_HITS` to 99, since Eduardo got an error when using the 100 setting, the requests failed, due to the `max_inner_result_window` limit (100).

When setting the inner hits of the query to `VIEW_MORE_CHILD_HITS + 1` in order to determine whether more entries exist and thus whether to display the button, the query fails. To avoid surpassing the limit, the fix is to set `VIEW_MORE_CHILD_HITS to 99`.

**Comment by mlissner** [comment]
So now it shows 99 items, and if there are more than that, it shows the button?

**Comment by albertisfu** [comment]
> So now it shows 99 items, and if there are more than that, it shows the button?

yeah, this is correct.

**Comment by mlissner** [comment]
WFM, if @ERosendo is happy!

**Review by ERosendo — APPROVED** [review]
The code looks good and It's working properly 👍 Thanks @albertisfu

**Pull request merged**
